Fusion-Power-Plant-Framework/bluemira

README.md

Adds a WIP message to the README. Split out from #528 because the picture isn't ready yet. I've spoken with @fabrizio-franza  and he is happy with the message.

Add WIP progress message to README.md

---

.readthedocs.yaml

Closes #537
Initial set up for readthedocs.
N/A

Initial setup for readthedocs

---

README.md
documentation/source/started.rst

Add process link to readme and docs

📝 add process url to readme and docs

---

BLUEPRINT/reactor.py
bluemira/base/look_and_feel.py
bluemira/codes/process/teardown.py
bluemira/equilibria/run.py
bluemira/fuel_cycle/lifecycle.py
bluemira/fuel_cycle/timeline.py
bluemira/geometry/_deprecated_base.py
documentation/source/_static/css/custom.css

See SonarCloud bug reports
Our [SonarCloud bug reports](https://sonarcloud.io/project/issues?id=Fusion-Power-Plant-Framework_bluemira&resolved=false&types=BUG) identify a few points where we are clearly performing assignments that do nothing, have unreachable code, or do not satisfy fallbacks. This looks to identify and fix most of those issues.
N/A

Fix some SonarCloud bugs

---

bluemira/utilities/fit_tools.py
tests/bluemira/utilities/test_fit_tools.py

In #566 it was requested to keep the surface_fit function. This generalises that function to N dimensional fit 
None, should work the same as before 

🎨 Generic surface fit

---

bluemira/geometry/coordinates.py
tests/bluemira/geometry/test_coordinates.py

hide Coordinates CCW test cos its temperamental..

---

documentation/source/base/components.rst
documentation/source/introduction.rst

CI was failing because of merge order and enabling of more tests
N/A

🚨 fix CI tests

---

bluemira/utilities/plot_tools.py

This ccw_check looks like it was missed

🐛 missed a ccw check import

---

BLUEPRINT/beams/model.py
BLUEPRINT/beams/node.py
BLUEPRINT/cad/cadtools.py
BLUEPRINT/nova/firstwall.py
BLUEPRINT/utilities/plottools.py
bluemira/base/constants.py
bluemira/codes/plasmod/api.py
bluemira/equilibria/coils.py
bluemira/equilibria/optimiser.py
bluemira/fuel_cycle/tools.py
bluemira/geometry/_deprecated_tools.py
bluemira/magnetostatics/circular_arc.py
tests/BLUEPRINT/cli/test_indir/SMOKE-TEST_template.json
tests/bluemira/geometry/test_deprecated_tools.py
tests/bluemira/magnetostatics/test_semianalytic_2d.py

With the update of versions we've run into a new set of deprecation warnings and the like.
I've run through the tests and tried to fix most of the warnings that we get. We stil get a bunch from some of our dependencies, sadly.
N/A

Fix a bunch of warnings across the codebase

---

bluemira/codes/interface.py
bluemira/codes/plasmod/api.py
bluemira/codes/utilities.py
examples/codes/run_plasmod_example.ipynb
examples/codes/run_plasmod_example.py

This ensures send and recv mappings are always up to date

🎨 update send and rev mappings

---

ACKNOWLEDGEMENTS.md
CITATION.cff

Closes #107 
Created from https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md.
May want to change authors from bluemira team to actual names

✨ Create a citation file

---

documentation/source/faq.rst
documentation/source/index.rst
documentation/source/ssh.rst

As title, sometimes port 22 doesnt work for github this adds some help. Also started an FAQ for some simple problems and solutions
N/A

Add some FAQs and some SSH help

---

documentation/source/faq.rst
documentation/source/installation.rst

Closes #699 
Added a few FAQs for zsh and MacOS to the docs
N/A

📝 doc fixes

---

tests/bluemira/builders/EUDEMO/test_pf_coils.py

Closes #703 (the test was bad, it actually works OK)
Fixes a test for the pf coil mapper
N/A

Fix PF coil mapper test

---

bluemira/codes/_freecadapi.py
bluemira/geometry/plane.py
tests/bluemira/geometry/test_plane.py

Closes #652 
Adds a classmethod to `BluemiraPlane` to instantiate from a matrix
Adds a classmethod to `BluemiraPlane` to instantiate from a matrix

Add `BluemiraPlane` from matrix

---

requirements-develop.txt

See https://github.com/tylerwince/flake8-bandit/   issue 21
Pin bandit until the flake8-bandit PR is merged.
None

⬇️ temporarily pin bandit

---

bluemira/__init__.py
bluemira/base/tools.py
bluemira/display/__init__.py
bluemira/equilibria/__init__.py
bluemira/mesh/meshing.py
requirements-develop.txt
setup.py

Enforcing absolute imports as per PEP8 recommendations
CI enforces absolute imports

🚨 flake8 absolute imports

---

.pre-commit-config.yaml

Pins bandit version in pre-commit YAML file, as it uses its own environment

Pin bandit==1.7.2 in pre-commit YAML

---

bluemira/utilities/plot_tools.py

fix on plot_tools.py

---

bluemira/fuel_cycle/blocks.py

Easy win for part of #767 
Removes unneeded global bluemira import
None

➖ remove unneeded import

---

bluemira/codes/ukaea_powerbalance/__init__.py
bluemira/codes/ukaea_powerbalance/api.py
bluemira/codes/ukaea_powerbalance/constants.py

Initial UKAEA PowerBalance model integration
This is a PR into a long(ish) lived feature branch `ukaea_powerbalance` hence the self review. Any changes to this can be put in a new PR to that branch
N/A

🏗️ initial skeleton of UKAEA powerbalance model

---

.github/workflows/ci.yml
bluemira/base/file.py
conftest.py

Enable private tests, may have never been enabled by accident
N/A

Enable private tests in CI

---

conda/environment.yml

fluids has been updated, not covered by dependabot
None

⬆️ conda update fluids

---

CODEOWNERS

closes #794 
Updates CODEOWNERS
N/A

Update CODEWONERS file

---

documentation/source/installation.rst

Pretty sure this isn't anywhere in our install docs and will cause errors when running some examples now.

Add line in installation documentation for msh2xdmf

---

data/equilibria/vertical_stability_data.json

Correct IDM path for reference report on A ratio elongation

---

tests/BLUEPRINT/systems/test_tfcoils.py

TF coil tests unbearably slow... let's save the planet.

Mark BLUEPRINT TF coil tests as long run

---

bluemira/radiation_transport/advective_transport.py
tests/bluemira/radiation_transport/test_advective_transport.py

Reverts Fusion-Power-Plant-Framework/bluemira#788 until the test is fixed, original branch restored for further work

Revert "Removing flux surface that doesn't intersect the wall"

---

bluemira/utilities/fit_tools.py

Sorted can take multiple conditions. Makes this sorting much simpler and maintainable
None

⚡️ sorted can take multiple key conditions

---

CODEOWNERS

Needs #843 
Too much noise group lists of individual names
Replaces reviewers with groups of reviewers
N/A

Update CODEOWNERS to use review groups.

---

scripts/install-process.sh

Hopefully Closes #838 
Pulls in an updated process and then checks out a branch
you should now be able to do `bash scripts/install-process.sh develop` if so desired

🐛 update process script

---

bluemira/codes/_nlopt_api.py

Remove mutable default arguments in NLOpt interface

---

bluemira/codes/__init__.py
bluemira/codes/wrapper.py

Dynamic wrapper for powerbalance solvers
None

✨ powerbalance dynamic wrapper

---

bluemira/base/config.py
bluemira/base/config_schema.py
bluemira/codes/interface.py
bluemira/codes/plasmod/api.py
bluemira/codes/plasmod/mapping.py
bluemira/codes/process/mapping.py
bluemira/codes/process/run.py
bluemira/codes/process/setup.py
bluemira/codes/utilities.py
data/reactors/EU-DEMO/systems_code/mockPROCESS.json
tests/bluemira/codes/process/test_data/mockPROCESS.json

Creates mappings to currently non existent bluemira parameters.
~This is based off #748 and that needs to be merged first~

Process powerbalance parameters

---

bluemira/base/config.py
bluemira/base/config_schema.py
bluemira/codes/interface.py
bluemira/codes/plasmod/api.py
bluemira/codes/plasmod/mapping.py
bluemira/codes/process/mapping.py
bluemira/codes/process/run.py
bluemira/codes/process/setup.py
bluemira/codes/utilities.py
data/reactors/EU-DEMO/systems_code/mockPROCESS.json
tests/bluemira/codes/process/test_data/mockPROCESS.json

Reverts Fusion-Power-Plant-Framework/bluemira#848
#867 @je-cook

Revert "Process powerbalance parameters"

---

CODEOWNERS

Add repo-review team to CODEOWNERS

---

bluemira/codes/process/PROCESS_DEFAULT_IN.DAT

Closes #750 
Modified DEMO 2018 baseline to remove fixed criteria.
A newer PROCESS input file, as generic as possible for now
None

🔧 Update default PROCESS input file

---

CODEOWNERS
bluemira/structural/plotting.py
tests/bluemira/structural/test_crosssection.py
tests/bluemira/structural/test_element.py
tests/bluemira/structural/test_geometry.py
tests/bluemira/structural/test_model.py
tests/bluemira/structural/test_node.py
tests/bluemira/structural/test_plotting.py
tests/bluemira/structural/test_transformation.py

Adds a review team entry for the structural module and removes some __main__ scripts

Cleanup of the structural module and CODEOWNERS entry

---

bluemira/equilibria/shapes.py

Remove duplicate variable in `JohnerLCFS`

---

bluemira/equilibria/opt_constraints.py

Closes #793 
Just adds in some functions for force and field constraints a la EU-DEMO. Not tested or threaded in yet, thought I'd split this down into smaller PRs.
None yet

Add force and field constraints

---

bluemira/codes/_freecadapi.py

`make_bspline` end check allclose not equality

---

bluemira/structural/geometry.py
tests/structural/test_geometry.py
tests/structural/test_plotting.py

Fix structural longrun tests and bug

---

bluemira/builders/EUDEMO/tf_coils.py
bluemira/builders/EUDEMO/vacuum_vessel.py
bluemira/builders/thermal_shield.py
bluemira/codes/_freecadapi.py
bluemira/geometry/tools.py
bluemira/utilities/positioning.py
tests/geometry/test_tools.py

Refactor `slice_shape` to use `BluemiraPlane`

---

tests/geometry/test_inscribed_rect.py

Closes #967 
Ran it 10 times with no failures..

Fix `inscribed_rect` test 

---

bluemira/geometry/tools.py

Fallback to make_polygon does not have correct default args

---

bluemira/codes/plasmod/api.py
bluemira/codes/plasmod/constants.py
tests/codes/plasmod/test_api.py

Closes #915 
Closes #914 
Fix the solver and and some tests
None

Plasmod solver fix and tests

---

tests/builders/EUDEMO/test_pf_coils.py

Resolve TODO from #747 now it is merged

---

conda/environment.yml
requirements.txt
setup.py

Moves gmsh to pip install 
None

🚚 Move gmsh to pip install

---

bluemira/codes/plasmod/PLASMOD_DEFAULT_IN.json

PLASMOD inputs file fuelhe3

---

bluemira/codes/plasmod/PLASMOD_DEFAULT_OUT.json

Requires a sister PR on PLASMOD

add jiter to default PLASMOD outputs

---

bluemira/magnetostatics/error.py
bluemira/magnetostatics/semianalytic_2d.py
bluemira/magnetostatics/tools.py
tests/magnetostatics/test_semianalytic_2d.py

Fix `semianalytic_Bz` for integration edge case

---

bluemira/codes/process/api.py
bluemira/codes/process/run.py
tests/codes/process/test_api.py

Needed for #601 
Extract data from process this should really be a generic interface to the database but for now WIP.
@DarioV86 this stuff can be called in you example script and then the data can be passed as input to your methods
@hsaunders1904 as your doing a lot of refactoring around here atm this can wait as you see fit (when its done) 
None

Process api additions

---

.github/dependabot.yml

🔨 change dependabot target branch and remove pinning

---

bluemira/base/config.py
bluemira/base/config_schema.py
bluemira/equilibria/flux_surfaces.py
tests/equilibria/test_flux_surfaces.py

Method to calculate the poloidal projection of the glancing.
Input: glancing angle.

Define glancing angle

---

bluemira/equilibria/equilibrium.py
bluemira/equilibria/physics.py

Remove some calculation methods from `Equilibrium`

---

documentation/source/faq.rst
scripts/update_dependencies.sh

A script to update the pip dependencies to whatever is on develop. Tries to fail as early as possible and tell the user. This does not touch conda
Use `bash scripts/update_dependencies.sh`

✨ script to update pip dependencies

---

bluemira/balance_of_plant/steady_state.py

Fixes balance_of_plant numpy warning

---

CODEOWNERS

Adds plasma-physics to the review list
None

🔧 Reorder and add plasma_physics review to CODEOWNERS

---

scripts/install-conda.sh

Closes #1211 
Same as #1210 but for local install.To update an existing install you need to install mamba and use it to create your env
```bash
conda install mamba -n base -c conda-forge
mamba env create --file conda/environment.yml
conda activate bluemira
```

🚑️ miniforge -> mambaforge for local install

---

setup.py

Bump numba scipy pin

---

.github/workflows/ci.yml
examples/design/EU-DEMO/EUDEMO_tests/test_reactor.py

I accidentally diabled the EUDEMO tests when #1207 went in

💚 run EUDEMO tests

---

bluemira/equilibria/shapes.py

Closes #1227
Remove mutable default in `JohnerLCFS`
N/A

Remove mutable default in `JohnerLCFS`

---

examples/equilibria/eudemo_2017.ipynb
examples/equilibria/eudemo_2017.py

The return of `sof.psi` and `eof.psi` are numbers not lists
None

🐛 Fix 2017 equilibria example

---

bluemira/base/builder.py
bluemira/base/designer.py
tests/base/test_builder.py

Adds Builder and Designer base classes

Add builder base classes

---

bluemira/base/parameter_frame/__init__.py
bluemira/base/parameter_frame/_decorator.py
bluemira/base/parameter_frame/_frame.py
bluemira/base/parameter_frame/_parameter.py
requirements.txt
setup.py
tests/base/parameterframe/test_parameter.py
tests/base/parameterframe/test_parameterframe.py

Adds new-style `ParameterFrame` MVP for use with the new builders.
Renamed to `NewParameterFrame` for the time-being, for peaceful co-existence with old `ParameterFrame`

Add new parameterframe

---

bluemira/base/builder.py
bluemira/builders/__init__.py
bluemira/builders/plasma.py
tests/builders/test_plasma.py

Restore the `PlasmaBuilder` using the new builder interface.
Note that this doesn't implement a designer.

Add bluemira plasma builder

---

bluemira/builders/cryostat.py
bluemira/builders/tools.py
tests/builders/test_cryostat.py

Cryostat with new builder 

---

bluemira/base/builder.py
bluemira/base/designer.py
bluemira/base/parameter_frame/__init__.py
bluemira/base/parameter_frame/_frame.py
tests/base/parameterframe/test_parameterframe.py

Refactor out some duplicate code. Unsure on the name and unsure whether I need to inherit from `abc` explicitly for `Designer` and `Builder`.

♻️ Refactor out some builder and designer methods

---

examples/design/EU-DEMO/EUDEMO_builders/blanket.py
examples/design/EU-DEMO/EUDEMO_tests/test_blanket.py

Recreate EUDEMO blanket, TODO: test

✨ EUDEMO blanket

---

bluemira/builders/cryostat.py
bluemira/builders/thermal_shield.py
bluemira/builders/tools.py
examples/design/EU-DEMO/EUDEMO_builders/vacuum_vessel.py
examples/design/EU-DEMO/EUDEMO_tests/test_vacuum_vessel.py
tests/builders/test_tools.py

Makes Vacuum vessel for EUDEMO, probably similar problems to thermal shield, TODO: tests

✨ EUDEMO vacuum vessel

---

bluemira/builders/radiation_shield.py
tests/builders/test_radiation_shield.py

✨ Radiation Shield new designer

---

bluemira/equilibria/coils.py
bluemira/equilibria/equilibrium.py
bluemira/equilibria/plotting.py
bluemira/structural/model.py
examples/fuel_cycle/EUDEMO_fuelcycle.ipynb
examples/fuel_cycle/EUDEMO_fuelcycle.py
tests/structural/test_model.py

Fix SonarCloud bugs that cause all PRs to fail when merged into `develop`

---

examples/design/EU-DEMO/EUDEMO_tests/test_reactor.py

Fix occasional CI failure due to approx on 0.0

---

bluemira/base/parameter_frame/_frame.py
tests/base/parameterframe/test_parameterframe.py

Closes #1430 
Pretty print of a parameterframe. I havent bothered with Parameter but that could be done too. Dunno if it would add much
None

🧑‍💻 Pretty print parameterframe

---

bluemira/base/error.py
bluemira/base/reactor.py
tests/builders/test_reactor.py

Adds a base class for a Bluemira reactor.

Add reactor base class

---

bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py

Fixed boundary equilibrium: optional plasma current scaling.

---

tests/equilibria/test_flux_surfaces.py

Fix flux surface test

---

.github/workflows/comments.yml

Closes #1485 
This passes on my fork. The changes themselves wont appear here until after its merged for security reasons around workflow run
Add a PR info finder action which seemed to fix everything from what I can tell.

🐛 Fix PR comment CI

---

.github/workflows/ci.yml
.github/workflows/comments.yml

Upgrades checkout action version and checkout for PR comments

🐛 Update checkout and add checkout to PR comments

---

bluemira/base/parameter_frame/_frame.py
bluemira/equilibria/equilibrium.py
bluemira/utilities/opt_variables.py
pyproject.toml
tests/geometry/test_parameterisations.py
tests/utilities/test_opt_variables.py

Pandas was not really used for anything important so removed the final couple of uses. It still seems to be a dependency of a dependency however
None

➖ Remove pandas as a direct dependency

---

.github/workflows/comments.yml

Ref report hash was empty. This should fix that

💚 Fix ref report download

---

.github/workflows/comments.yml

🐛 fix PR comment attempt N 🤯️

---

.github/workflows/comments.yml

phfff
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
https://stackoverflow.com/questions/74137120/how-to-fix-or-avoid-error-unable-to-process-file-command-output-successfully

🐛 multiline PR comment hack

---

documentation/source/base/parameter.rst
documentation/source/conventions.rst

Part of #1426 
Updated documentation for Parameter and ParameterFrame

📝 Parameter and ParameterFrame documentation

---

CONTRIBUTING.md

Closes #90 
A brief overview of our import style
None

📝 Add import style to CONTRIBUTING.md

---

.github/workflows/ci.yml

For some reason dependabot didnt pick this up

⬆️ update actions/cache to v3

---

documentation/source/base/base.rst
documentation/source/base/components.rst
documentation/source/base/design_build.dot
documentation/source/base/design_build.rst
documentation/source/index.rst
documentation/source/introduction.rst
documentation/source/mesh/mesh.rst

part of #760
Adds some documentation for the new builder designer architecture. Also adds some high level architecture intro stuff
None

📝 Designer and Builder documentation

---

documentation/source/base/components.rst
documentation/source/base/design_build.dot

Componet and ComponentManager docs, based off #1567 
None

📝 Component and ComponentManager

---

documentation/developer/adr/0002-record-design-stage.md

ADR for `DesignStage`

---

documentation/developer/adr/0003-record-component-manager.md

ADR `ComponentManager`

---

documentation/developer/adr/0004-record-parameter-frame.md

ADR for `ParameterFrame`

---

eudemo/config/build_config.json
eudemo/config/params.json
eudemo/eudemo/params.py
eudemo/eudemo/pf_coils/designer.py

Add missing `PFCoilDesigner` parameters

---

bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py

Fix Ip scaling in fixed boundary equilibrium solver

---

README.md

At present our terms of use are a little unclear. I don't think the intention was ever to force co-authorships for any already existing and documented functionality.
My view is if the functionality is already there (and soon to be described in a publication) then citation is sufficient. If, in the process of some external person preparing a publication and we provide support in terms of adding new functionality, then those who were involved in doing that new work should be _offered_ co-authorship.
Update the README to clarify the above.

Proposal: Important tweaks to terms of use

---

bluemira/codes/plasmod/mapping.py
bluemira/codes/plasmod/params.py
bluemira/codes/process/mapping.py
bluemira/codes/process/params.py
tests/codes/plasmod/data/params.json
tests/codes/process/test_data/params.json

Add `PsepB_qAR_max` to PROCESS and PLASMOD apis

---

eudemo/eudemo_tests/ivc/test_divertor_silhouette.py
eudemo/eudemo_tests/pf_coils/test_tools.py

Fix tests in EUDEMO feature branch

---

documentation/source/developer/EU-DEMO_params.rst
documentation/source/developer/parameterisations.rst
documentation/source/index.rst

Remove EUDEMO parameterisation documentation

---

bluemira/equilibria/equilibrium.py
bluemira/equilibria/plotting.py

Fixes a couple of issues, namely in `plot_field` and `plot_core` which just were not working for various silly reasons...

Fix a couple of plotting bugs in equilibria

---

.github/workflows/ff.yml

Closes #1486
test repo: https://github.com/je-cook/ci_test
When we merge dependencies into develop at the moment its a bit hacky, this makes it better 

👷 fast-forward merge for dependencies

---

.pre-commit-config.yaml

precommit versions havent been updated automatically. Just bumping them in line with requirements.
We should see in dependabot can deal with this

⬆️ update precommit versions

---

documentation/developer/adr/0005-record-cache-vs-recreate.md

ADR for caching

---

bluemira/codes/plasmod/__init__.py
examples/codes/run_plasmod_example.ipynb
examples/codes/run_plasmod_example.py

Plasmod codes example broke with #1688 with this it runs

🐛 fix plasmod example

---

bluemira/equilibria/fem_fixed_boundary/equilibrium.py
bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
bluemira/equilibria/fem_fixed_boundary/utilities.py

Swap out scipy optimiser for NLOpt in FEM fixed boundary equilibria magnetic axis finding

---

bluemira/equilibria/opt_constraint_funcs.py
bluemira/equilibria/opt_constraints.py
examples/equilibria/eudemo_2017.ipynb
examples/equilibria/eudemo_2017.py
examples/equilibria/single_null.ipynb
examples/equilibria/single_null.py

Fix force units for ForceConstraint

---

bluemira/codes/plasmod/api/_plotting.py
bluemira/equilibria/fem_fixed_boundary/equilibrium.py
bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
bluemira/utilities/plot_tools.py
examples/codes/run_plasmod_example.py
examples/equilibria/fem_fixed_boundary/equilibrium_example.py
tests/codes/plasmod/test_solver.py
tests/equilibria/fem_fixed_boundary/test_equilibrium.py

Fixed boundary equilibrium plotting

---

documentation/source/conf.py
scripts/copyright_update.py

Documentation copyright footer wasnt updated. This modifies the script to change it and updates the copyright footer.
fyi @CoronelBuendia 

🐛 fix docs copyright

---

documentation/source/mesh/mesh.rst

Update meshing documentation

---

eudemo/README.md

Explicitly state EUDEMO is WIP

📝 EUDEMO WIP message

---

bluemira/equilibria/coils/_coil.py
bluemira/equilibria/coils/_grouping.py
bluemira/equilibria/run.py
eudemo/eudemo/pf_coils/designer.py
eudemo/eudemo/pf_coils/tools.py
tests/equilibria/test_coils.py
tests/equilibria/test_run.py

Missed probably because we don't have many tests of equilibria/run, will add some before I take this out of draft
None

🐛 Fix bug in equilibria run from bad conversion to new coilset

---

bluemira/codes/plasmod/api/_solver.py
tests/codes/plasmod/test_solver.py

Scale all PLASMOD profiles, not just flux functions and psi.

---

bluemira/base/parameter_frame/_frame.py
bluemira/magnetostatics/circuits.py
bluemira/plasma_physics/scaling_laws.py
tests/base/parameterframe/test_parameterframe.py

Makes ParameterFrame tabulate output formatted floats and other minor code quality changes
None

ParameterFrame print formatting and other minor cleanup

---

bluemira/base/constants.py
bluemira/magnetostatics/greens.py
documentation/source/magnetostatics/magnetostatics.rst
tests/magnetostatics/test_greens.py

Add Greens functions for dpsi/dx and dpsi/dz

---

.github/workflows/comments.yml

Removes the remaining deprecation warnings from our CI

⬆️ Update gh-action get-workflow-origin dep

---

bluemira/codes/process/_teardown.py
eudemo/eudemo/params.py
tests/codes/process/test_teardown.py

There was a small bug if the process run failed

🐛 fix process fail checker

---

bluemira/magnetostatics/greens.py

Fix equation docstring rendering in magnetostatics API documentation

---

bluemira/equilibria/shapes.py
tests/equilibria/test_shapes.py

Add `ManickamLCFS` and `CunninghamLCFS` geometry parameterisations

---

CITATION.cff
examples/design/simple_reactor.ex.py

Closes #{ID}
Fixes type in example

Fix typing in simple reactor example

---

eudemo/config/build_config.json
eudemo/config/mockPROCESS.json

Avoid dolfin bug in EUDEMO

---

bluemira/geometry/tools.py
tests/geometry/test_tools.py

Fix closed triangle bug in `make_polygon`

---

README.md
documentation/source/bluemira-roadmap-dark.svg
documentation/source/bluemira-roadmap.svg
documentation/source/introduction.rst

This updates our roadmap and also makes the roadmap visible when using github darkmode. Friday morning messing :)
None 

Update our roadmap

---

CONTRIBUTING.md
README.md

Strips out the changes from #1983 that are not PROCESS related

📝 Fixup README and Contributing

---

.pre-commit-config.yaml

Updates the version in our pre-commit config

⬆️ update precommit check versions

---

.flake8

Remove mirapy from flake8 exclude

---

bluemira/builders/coil_supports.py
bluemira/builders/cryostat.py
bluemira/builders/divertor.py
bluemira/builders/pf_coil.py
bluemira/builders/plasma.py
bluemira/builders/radiation_shield.py
bluemira/builders/thermal_shield.py
bluemira/builders/tools.py
eudemo/config/PFCoilDesign.json
eudemo/eudemo/blanket.py
eudemo/eudemo/tf_coils/tf_coils.py
eudemo/eudemo/tools.py
eudemo/eudemo/vacuum_vessel.py

Fix EUDEMO display colors for plotting and planar CAD

---

bluemira/codes/_freecadapi.py
bluemira/geometry/face.py
bluemira/geometry/shell.py
bluemira/geometry/solid.py
tests/geometry/test_face.py

Add `BluemiraFace.normal_at`

---

bluemira/builders/tf_coils.py
tests/builders/test_tf_coils.py

Closes #{ID}
I missed a new warning in the tf coil builder from matplotlib and I've changed the bluemira warning to a deprecation warning which it is more than a code warning.

🚨 fix warnings in tf coil builder

---

bluemira/base/builder.py
bluemira/base/designer.py
bluemira/base/tools.py
bluemira/builders/coil_supports.py
bluemira/builders/pf_coil.py
eudemo/eudemo/reactor.py
tests/base/test_designer.py
tests/base/test_tools.py

Adds timing shown only in debugging logging for all designers and builders

🧑‍💻 Time all design and build stages in debug output

---

bluemira/base/builder.py
bluemira/base/components.py
bluemira/base/constants.py
bluemira/base/error.py
bluemira/base/file.py
bluemira/base/logs.py
bluemira/base/look_and_feel.py
bluemira/base/parameter_frame/_frame.py
bluemira/base/parameter_frame/_parameter.py
bluemira/base/reactor_config.py
bluemira/base/tools.py

This adds all the basic types for the base module that we were missing. It doesnt do anything fancy but is the start of bringing us closer to having full typing
None

🏷️ typing improvements for base

---

tests/equilibria/fem_fixed_boundary/test_fem_magnetostatic_2D.py

With #1949 we could no longer run tests in parallel with `pytest-xdist` because the mesh file tries to be created multiple times on test collection. Once tests are parameterised in the collection they get split up logically so this problem is sidestepped. 
This modifies a couple of tests to make lazy style fixtures and use setup_method where appropriate.

✅ Allow all tests to run in parallel

---

bluemira/equilibria/equilibrium.py

Add psi norm tolerance to `Equilibrium` methods for LCFS and separatrix finding.

---

bluemira/geometry/coordinates.py
tests/geometry/test_coordinates.py

Make `Coordinates` support lines and vertices

---

CONTRIBUTING.md
bluemira/plasma_physics/scaling_laws.py

Docstring convention update: colons good, types in typehints

---

bluemira/plasma_physics/collisions.py
bluemira/plasma_physics/reactions.py
bluemira/plasma_physics/rules_of_thumb.py

Docstring convention enforcement marathon - part 1

---

bluemira/equilibria/opt_problems.py
bluemira/magnetostatics/baseclass.py
bluemira/magnetostatics/biot_savart.py
bluemira/magnetostatics/circuits.py
bluemira/magnetostatics/circular_arc.py
bluemira/magnetostatics/finite_element_2d.py
bluemira/magnetostatics/greens.py
bluemira/magnetostatics/semianalytic_2d.py
bluemira/magnetostatics/tools.py
bluemira/magnetostatics/trapezoidal_prism.py

Docstring convention enforcement marathon - part 3

---

bluemira/materials/cache.py
bluemira/materials/material.py
bluemira/materials/mixtures.py

Docstring convention enforcement marathon - part 4

---

bluemira/base/builder.py
bluemira/base/components.py
bluemira/base/constants.py
bluemira/base/designer.py
bluemira/base/file.py
bluemira/base/logs.py
bluemira/base/look_and_feel.py
bluemira/base/reactor.py
bluemira/base/reactor_config.py
bluemira/base/tools.py

Docstring convention enforcement marathon - part 6

---

bluemira/builders/_varied_offset.py
bluemira/builders/coil_supports.py
bluemira/builders/cryostat.py
bluemira/builders/pf_coil.py
bluemira/builders/plasma.py
bluemira/builders/tf_coils.py
bluemira/builders/thermal_shield.py
bluemira/builders/tools.py

Docstring convention enforcement marathon - part 8

---

bluemira/utilities/fit_tools.py
bluemira/utilities/plot_tools.py
bluemira/utilities/positioning.py
bluemira/utilities/tools.py

Closes #{ID}
I have deliberately not touched the optimisation stuff, for @hsaunders1904 future sanity

Docstring convention enforcement marathon - part 9

---

bluemira/balance_of_plant/calculations.py
bluemira/balance_of_plant/steady_state.py

Docstring convention enforcement marathon - part 7

---

bluemira/equilibria/boundary.py
bluemira/equilibria/coils/_coil.py
bluemira/equilibria/coils/_field.py
bluemira/equilibria/coils/_grouping.py
bluemira/equilibria/coils/_tools.py
bluemira/equilibria/equilibrium.py
bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
bluemira/equilibria/fem_fixed_boundary/file.py
bluemira/equilibria/fem_fixed_boundary/utilities.py
bluemira/equilibria/file.py
bluemira/equilibria/find.py
bluemira/equilibria/flux_surfaces.py
bluemira/equilibria/grad_shafranov.py
bluemira/equilibria/limiter.py
bluemira/equilibria/num_control.py
bluemira/equilibria/opt_constraint_funcs.py
bluemira/equilibria/opt_constraints.py
bluemira/equilibria/opt_objectives.py
bluemira/equilibria/physics.py
bluemira/equilibria/plasma.py
bluemira/equilibria/positioner.py
bluemira/equilibria/profiles.py
bluemira/equilibria/run.py
bluemira/equilibria/shapes.py
bluemira/equilibria/solve.py

Docstring convention enforcement marathon - part 5

---

bluemira/structural/crosssection.py
bluemira/structural/element.py
bluemira/structural/geometry.py
bluemira/structural/loads.py
bluemira/structural/material.py
bluemira/structural/matrixops.py
bluemira/structural/model.py
bluemira/structural/node.py
bluemira/structural/plotting.py
bluemira/structural/result.py
bluemira/structural/stress.py
bluemira/structural/symmetry.py
bluemira/structural/transformation.py

Docstring convention enforcement marathon - part 10

---

bluemira/fuel_cycle/analysis.py
bluemira/fuel_cycle/blocks.py
bluemira/fuel_cycle/cycle.py
bluemira/fuel_cycle/lifecycle.py
bluemira/fuel_cycle/timeline.py
bluemira/fuel_cycle/timeline_tools.py
bluemira/fuel_cycle/tools.py

Docstring convention enforcement marathon - part 11

---

bluemira/codes/_freecadapi.py
bluemira/codes/_nlopt_api.py
bluemira/codes/_polyscope.py
bluemira/codes/interface.py
bluemira/codes/params.py
bluemira/codes/plasmod/api/_inputs.py
bluemira/codes/plasmod/api/_plotting.py
bluemira/codes/plasmod/api/_run.py
bluemira/codes/plasmod/api/_setup.py
bluemira/codes/plasmod/api/_solver.py
bluemira/codes/plasmod/api/_teardown.py
bluemira/codes/plasmod/equilibrium_2d_coupling.py
bluemira/codes/process/_plotting.py
bluemira/codes/process/_run.py
bluemira/codes/process/_setup.py
bluemira/codes/process/_solver.py
bluemira/codes/process/_teardown.py
bluemira/codes/process/api.py
bluemira/codes/utilities.py
bluemira/codes/wrapper.py

Docstring convention enforcement marathon - part 12

---

bluemira/codes/_freecadapi.py
bluemira/geometry/compound.py
bluemira/geometry/tools.py
tests/geometry/test_tools.py

Add `boolean_fragments` to geometry module

---

bluemira/codes/_freecadapi.py
bluemira/geometry/wire.py
tests/geometry/test_wire.py

Handle `BluemiraWire.discretize()` with `ndiscr=1` and fix 3, 3 bug.

---

eudemo/eudemo/blanket/builder.py
eudemo/eudemo/blanket/designer.py
eudemo/eudemo/blanket/panelling/_designer.py
eudemo/eudemo/blanket/panelling/_opt_problem.py
eudemo/eudemo/blanket/panelling/_paneller.py
eudemo/eudemo/blanket/panelling/_pivot_string.py
eudemo/eudemo/equilibria/_designer.py
eudemo/eudemo/equilibria/tools.py
eudemo/eudemo/ivc/divertor_silhouette.py
eudemo/eudemo/ivc/ivc_boundary.py
eudemo/eudemo/ivc/plasma_face.py
eudemo/eudemo/ivc/wall_silhouette.py
eudemo/eudemo/maintenance/equatorial_port.py
eudemo/eudemo/maintenance/upper_port.py
eudemo/eudemo/pf_coils/tools.py
eudemo/eudemo/radial_build.py
eudemo/eudemo/tf_coils/tf_coils.py

Docstring convention enforcement marathon - part 14

---

bluemira/geometry/_private_tools.py
bluemira/geometry/_pyclipper_offset.py
bluemira/geometry/base.py
bluemira/geometry/bound_box.py
bluemira/geometry/compound.py
bluemira/geometry/coordinates.py
bluemira/geometry/face.py
bluemira/geometry/inscribed_rect.py
bluemira/geometry/parameterisations.py
bluemira/geometry/placement.py
bluemira/geometry/plane.py
bluemira/geometry/shell.py
bluemira/geometry/solid.py
bluemira/geometry/tools.py
bluemira/geometry/wire.py

Docstring convention enforcement marathon - part 13

---

bluemira/codes/_freecadapi.py
bluemira/geometry/base.py
tests/geometry/test_bound_box.py

Add `_tessellate` and `get_optimal_bounding_box` to `BluemiraGeo

---

bluemira/optimisation/_nlopt/functions.py
bluemira/optimisation/_nlopt/optimiser.py
bluemira/optimisation/_optimiser.py
tests/optimisation/test_nlopt.py
tests/optimisation/test_optimise.py

Add `f_x` to `OptimiserResult` and keep track of function call value history

---

bluemira/mesh/meshing.py
bluemira/mesh/tools.py

Docstring convention enforcement marathon - part 2

---

bluemira/base/parameter_frame/_frame.py
tests/base/parameterframe/test_parameterframe.py

Closes #1940 
Adds a new method to ParameterFrame to get the values of more than one parameter at once.
Also a little bit of a tidy up in the tests

✨ Get multiple values from frame

---

examples/design/simple_reactor.ex.py

Port `MyTFCoilOptProblem` in new optimisation feature branch

---

bluemira/base/reactor_config.py
eudemo/config/build_config.json
eudemo/eudemo/reactor.py
tests/base/reactor_config/data/nest_a/nest_a.config.json
tests/base/reactor_config/data/nest_a/nest_a.params.json
tests/base/reactor_config/data/nest_b/nest_b.config.json
tests/base/reactor_config/data/nest_b/nest_b_inner/nest_b.params.json
tests/base/reactor_config/data/reactor_config.nested_config.json
tests/base/reactor_config/data/reactor_config.nested_params.json
tests/base/reactor_config/data/reactor_config.nesting.json
tests/base/reactor_config/data/reactor_config.test.json
tests/base/reactor_config/test_reactor_config.py

Based on #2187
Closes #2187
Allows values in config files to be paths to nested files.

Reactor Config: add file reading feature

---

documentation/source/base/components.rst

Gives a bit more clarity to why `ComponentManager` and `Reactor` exist, especially as our `Component` example creates a component called `Reactor`.

📝 Improve base docs

---

bluemira/optimisation/_optimise.py
bluemira/optimisation/problem.py
eudemo/eudemo/blanket/panelling/_designer.py
eudemo/eudemo/blanket/panelling/_opt_problem.py
tests/optimisation/test_optimise.py
tests/optimisation/test_problem.py

Closes #2225 
Part of #2189 
Update the optimisation for the EUDEMO panelling to use the new optimisation interface.
This change adds the ability to suppress constraint violation warnings, as this was needed to replicate the previous optimiser's behaviour.

Update panelling optimisation for new interface

---

documentation/source/bluemira-roadmap-dark.svg
documentation/source/bluemira-roadmap.svg

📝 Update roadmap

---

bluemira/optimisation/_geometry/optimise.py
bluemira/optimisation/_geometry/problem.py

#2257
Forgot to add these in #2257, oops.

Add check constraints options to optimise_geometry

---

bluemira/equilibria/physics.py
bluemira/plasma_physics/rules_of_thumb.py
tests/plasma_physics/test_rules_of_thumb.py

Add q* and l_i 0-D calculations from Uckan and Wesson

---

bluemira/geometry/tools.py

Correct signed distance function docstrings

---

bluemira/equilibria/equilibrium.py

Remove `EQ_FOLDER`

---

bluemira/optimisation/_nlopt/optimiser.py
tests/optimisation/test_nlopt.py

Closes #2256 
Adds the error handling we had in the old optimiser to the new optimisation module.

Improve optimisation module error handling

---

bluemira/utilities/fit_tools.py

Enforce ij indexing in `surface_fit`

---

eudemo/config/build_config.json
eudemo/eudemo/maintenance/lower_port/builder.py
eudemo/eudemo/maintenance/lower_port/duct_designer.py
eudemo/eudemo_tests/maintenance/test_lower_port.py

Impl. new logic for offsetting the corner of the straight duct

---

bluemira/optimisation/_geometry/optimise.py

Closes #2417 
Removes x from `GeomOptimisationResult` there may be a cleaner version of this but it works

🎨 Remove x from GeomOptimisationResult

---

bluemira/equilibria/opt_constraint_funcs.py
bluemira/equilibria/optimisation/constraint_funcs.py

🐛 Minor fixes

---

bluemira/equilibria/opt_constraint_funcs.py
bluemira/equilibria/optimisation/__init__.py
examples/design/simple_reactor.ex.py
examples/equilibria/Spherical_Approximation_how_it_works.ex.py
examples/equilibria/spherical_harmonic_approximation_basic_function_check.ex.py
examples/optimisation/geometry_optimisation.ex.py

Closes #{ID}
Fixes some issues delaying the release

🐛 Fix broken examples and docstring issues

---

bluemira/equilibria/harmonics.py
bluemira/equilibria/optimisation/constraint_funcs.py
bluemira/equilibria/optimisation/objectives.py
bluemira/equilibria/optimisation/problem/_nested_position.py
bluemira/equilibria/optimisation/problem/_position.py
bluemira/equilibria/optimisation/problem/_tikhonov.py
bluemira/geometry/optimisation/_optimise.py
bluemira/geometry/parameterisations.py
bluemira/optimisation/_tools.py
bluemira/utilities/opt_tools.py
examples/equilibria/Spherical_Approximation_how_it_works.ex.py
examples/equilibria/spherical_harmonic_approximation_basic_function_check.ex.py
tests/equilibria/test_optimiser.py

Remove RegionMapper from new optimisation interface and deprecate some more things

---

bluemira/codes/plasmod/equilibrium_2d_coupling.py
bluemira/equilibria/equilibrium.py
bluemira/equilibria/fem_fixed_boundary/utilities.py
bluemira/equilibria/optimisation/objectives.py
bluemira/equilibria/optimisation/problem/_breakdown.py
bluemira/equilibria/optimisation/problem/_minimal_current.py
bluemira/equilibria/optimisation/problem/_nested_position.py
bluemira/equilibria/optimisation/problem/_position.py
bluemira/equilibria/optimisation/problem/_tikhonov.py
bluemira/equilibria/optimisation/problem/base.py
bluemira/equilibria/run.py
bluemira/equilibria/solve.py
bluemira/geometry/optimisation/_optimise.py
bluemira/geometry/optimisation/problem.py
bluemira/optimisation/__init__.py
bluemira/optimisation/_algorithm.py
bluemira/optimisation/_nlopt/optimiser.py
bluemira/optimisation/_optimise.py
bluemira/optimisation/problem.py
eudemo/config/build_config.json
eudemo/eudemo/comp_managers.py
eudemo/eudemo/equilibria/_designer.py
eudemo/eudemo/equilibria/tools.py
eudemo/eudemo/ivc/wall_silhouette.py
eudemo/eudemo/pf_coils/designer.py
eudemo/eudemo/reactor.py
eudemo/eudemo/tf_coils/tf_coils.py
eudemo/eudemo_tests/ivc/test_wall_silhouette.py
tests/codes/plasmod/test_profiles.py
tests/equilibria/test_run.py

Switches over to new optimisation API internally for remaining modules
Aims to be none

✨ Use new optimiser in internal modules

---

bluemira/equilibria/optimisation/constraints.py

Closes #{ID}
Converts the existing SH constraint so its using the new constraint mechanics

Convert SH constraint to new optimiser interface

---

.github/ISSUE_TEMPLATE/eu_demo_feature_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/step_feature_request.md

Modifies the feature request templates to try and get to the reasons behind any given feature request

📝 Add user story to feature requests

---

bluemira/utilities/tools.py
tests/utilities/test_tools.py

Adds a helper decorator/function to make deprecating things easier. Possibly in future we could have another function for if we're deprecating a module...

✨ Add deprecation helper function

---

bluemira/plasma_physics/reactions.py

A bit of cleanup and the dataclasses didnt work as a dataclass is intended to work. Now fixed

🎨 Fixup reactions dataclasses

---

bluemira/equilibria/shapes.py

While undertaking #2516 this seemed a bit larger than a couple of line changes. 
This will require checking with a fine toothed comb!
I've checked manually, with the figures and with np.allclose

♻️ Johner equilibria shape refactor

---

documentation/source/base/design_build.rst

Closes #2066 
Adds sector CAD recommendation to the builder docs

📝 Add CAD sector convention to the docs

---

eudemo/eudemo/maintenance/port_plug.py
requirements-conda.txt
requirements-develop.txt
requirements-examples.txt
requirements.txt
tests/codes/test_freecadapi.py
tests/materials/test_material.py

Update develop's dependencies for the next development cycle.

Dependency update after v1.6.0

---

README.md

add one-liner to README for optimisation module

---

eudemo/eudemo_tests/ivc/test_divertor_silhouette.py
tests/base/parameterframe/test_parameterframe.py
tests/base/reactor_config/test_reactor_config.py
tests/codes/plasmod/test_equilibrium.py
tests/codes/plasmod/test_solver.py
tests/codes/test_freecadapi.py
tests/display/test_plotter.py
tests/equilibria/test_flux_surfaces.py
tests/equilibria/test_harmonics.py
tests/equilibria/test_run.py
tests/geometry/test_coordinates.py
tests/geometry/test_geometry.py
tests/geometry/test_offset.py
tests/geometry/test_private_tools.py
tests/magnetostatics/test_trapezoidal_prism.py
tests/materials/test_material.py
tests/plasma_physics/test_reactions.py
tests/plasma_physics/test_scaling_laws.py
tests/structural/test_crosssection.py
tests/utilities/test_opt_variables.py

Appeases sonarcloud's new code quality rules a bit

🚨 Appease sonarcloud

---

bluemira/codes/_freecadapi.py
bluemira/equilibria/find.py
bluemira/equilibria/harmonics.py
bluemira/equilibria/plotting.py
bluemira/equilibria/profiles.py
bluemira/equilibria/solve.py
bluemira/fuel_cycle/lifecycle.py
bluemira/fuel_cycle/tools.py
tests/base/parameterframe/test_parameter.py
tests/base/parameterframe/test_parameterframe.py
tests/geometry/test_inscribed_rect.py

🚨 More sonarcloud

---

tests/codes/plasmod/test_solver.py
tests/codes/test_freecadapi.py

🚨🤞 this is the last

---

bluemira/magnetostatics/biot_savart.py
bluemira/magnetostatics/greens.py
tests/magnetostatics/test_biot_savart.py

Improve self-inductance calculation and fix bug in `circular_coil_inductance_elliptic`

---

bluemira/neutronics/neutronics_axisymmetric.py
bluemira/neutronics/params.py
bluemira/neutronics/result_presentation.py
bluemira/neutronics/tallying.py
examples/radiation_transport/neutronics.ex.py

Fixes to #1710
Fixed a few multiplication errors in the presentation of the results, and added comments
None

Minor error fixes to the outputted tables

---

tests/magnetostatics/test_polyhedral_prism.py

added test to check whether combined shape matching single shape

---

bluemira/equilibria/optimisation/constraints.py

Bugfix bizarre `np.zeros_like[x]` bug

---

bluemira/equilibria/optimisation/problem/_tikhonov.py

Bugfix control coils only in Tikhonov unconstrained and actually calculate f_x

---

bluemira/equilibria/optimisation/problem/base.py
bluemira/equilibria/plasma.py

Bugfix `TikhonovCOP` and base optimisation class to consider control coils only.

---

bluemira/equilibria/plasma.py
tests/equilibria/test_equilibrium.py

I've checked all close at every stage and they're the same 
Before change:
After change:
None

⚡️ 10x speed up plasma convolve

---

bluemira/magnetostatics/circuits.py
tests/magnetostatics/test_circuits.py
tests/magnetostatics/test_polyhedral_prism.py
tests/magnetostatics/tools.py

Add `ArbitraryPlanarPolyhedralXSCircuit`

---

.github/workflows/examples.yml
bluemira/codes/process/api.py
documentation/source/examples.rst
examples/codes/run_process_example.ex.py
tests/codes/process/test_api.py
tests/codes/process/test_data/mfile_data.json

Add PROCESS API example

---

bluemira/equilibria/coils/_coil.py
bluemira/equilibria/coils/_grouping.py
tests/equilibria/test_equilibrium.py

Closes #2724, which stems from #2721.
Passive coils no longer require manually setting.
None, no API changes.

Fixed the passive coils so they no longer require manual setting

---

CONTRIBUTING.md
README.md
pyproject.toml
tests/structural/test_model.py

This adds a bit more information on our tests to CONTRIBUTING.md and removes some unneeded test flagging.
also adds the info for #2725 

📝 Update CONTRIBUTING for more test info

---

CONTRIBUTING.md

Fix a couple of formatting issues I added into CONTRIBUTING

📝 Fix CONTRIBUTING formatting

---

eudemo/config/params.json
eudemo/eudemo/radial_build.py

PROCESS inputs tweaks for EU-DEMO 

---

bluemira/builders/coil_supports.py
bluemira/codes/_freecadapi.py
bluemira/equilibria/coils/_field.py
bluemira/equilibria/plotting.py
bluemira/geometry/tools.py
eudemo/config/params.json
eudemo/eudemo/pf_coils/tools.py
eudemo/eudemo/radial_build.py

Attempted hacks:
- np.where/nonzero of 1 and 2 element array indexing
- tf coil offset_wire hacking
also adds plotting for current=0 coils

🚧 Get EUDEMO running

---

bluemira/codes/process/_run.py
bluemira/codes/utilities.py
documentation/source/bluemira-roadmap-dark.svg
documentation/source/bluemira-roadmap.svg
documentation/source/installation.rst
eudemo/eudemo/radial_build.py
scripts/install-process.sh
tests/codes/process/test_api.py
tests/codes/process/test_run.py

📝 PROCESS documentation and roadmap update

---

bluemira/codes/process/_run.py

✅ Fix longrun process test

---

.github/workflows/examples.yml

Examples CI broken by shenanigans with only_tar_bz2 see #2864 for more info

🐛 Fix examples CI

---

tests/equilibria/test_equilibrium.py

Improve test coverage for EQDSK saving from `Equilibrium`

---

.github/workflows/ci.yml

Codecov v4 api broke upload and I didnt notice this should fix it. Need to check the CI run for upload succeeding (you will need to dig down as it will always pass on a branch)

🐛 Fix codecov upload

---

examples/README.md

Add to examples README

---

README.md
documentation/source/bluemira-roadmap-dark.svg
documentation/source/bluemira-roadmap.svg
documentation/source/introduction.rst

Updates the current projected plan for the next 4 quarters

📝 Plan update Q1 24

---

bluemira/geometry/coordinates.py

📝 More documentation on 3x3 matrices

---

bluemira/equilibria/optimisation/harmonics/__init__.py
bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
bluemira/geometry/tools.py
examples/equilibria/Spherical_Approximation_how_it_works.ex.py
examples/equilibria/spherical_harmonic_approximation_basic_function_check.ex.py
tests/equilibria/test_harmonics.py

Better defaults and catches and contiunes on not being able to find an LCFS during the approximation.
Closes #{ID}

Catch on unable to find LCFS & SH function interface

---

bluemira/balance_of_plant/steady_state.py
bluemira/base/reactor_config.py
bluemira/codes/params.py
bluemira/codes/plasmod/params.py
bluemira/codes/process/_solver.py
bluemira/codes/process/params.py
bluemira/equilibria/coils/_field.py
bluemira/equilibria/coils/_grouping.py
bluemira/equilibria/shapes.py
bluemira/fuel_cycle/cycle.py
bluemira/fuel_cycle/lifecycle.py
bluemira/geometry/base.py
bluemira/geometry/optimisation/_optimise.py
bluemira/geometry/optimisation/problem.py
bluemira/optimisation/_optimise.py
bluemira/plasma_physics/rules_of_thumb.py
bluemira/radiation_transport/advective_transport.py
bluemira/utilities/tools.py

Solves comment in  #1043 . Only partially address issue #1043 at this stage, which is too big to tackle in a single PR.
Fixed all of the places where :func:, :meth:, and :class: tags weren't linked properly.
None

Fixed the :func:, :meth:, and :class: tags

---

bluemira/base/designer.py
bluemira/codes/_freecadapi.py
bluemira/geometry/tools.py

Adds axis to 3p arc.
Closes #{ID}

added axis to 3p arc

---

bluemira/equilibria/optimisation/constraint_funcs.py
tests/equilibria/test_constraint_functions.py

Add more tests for constraints #2961

Constraints - add more tests

---

bluemira/base/builder.py

String in >=3.10 has a `removesuffix` method 

---

bluemira/geometry/coordinates.py
pyproject.toml
requirements-develop.txt
requirements-examples.txt
requirements.txt

Cleans up dependencies and bumps packages previously blocked

Python3.10 dependency cleanup

---

.pre-commit-config.yaml
CITATION.cff

This hopefully makes zenodo happy for the release DOI as its more standard to not use '+'

📄 Licence shorthand change for zenodo

---

bluemira/codes/process/_inputs.py
bluemira/codes/process/_run.py
bluemira/codes/process/_solver.py
bluemira/codes/process/equation_variable_mapping.py
eudemo/eudemo/radial_build.py
examples/codes/run_process_example.ex.py
scripts/install-process.sh
tests/codes/process/test_data/mfile_data.json

Modifications to the PROCESS api that will break our interface on the next release

👽 Changes required for next release of PROCESS

---

examples/magnetostatics/finite_element_2D_single_coil.ex.py
scripts/run_examples.py

Examples CI was failing because of pyvista segfault due to no framebuffer

🐛 Catch pyvista segfault

---

pyproject.toml

Ignore numba decorated calls as coverage can't currently be resolved awaiting numba#4268 

🩺 Ignore numba coverage

---

.github/workflows/actions/build/action.yml

Closes #{ID}
The CI fails to run if coming from a forked repo due to a misconfigured if condition.

CI fix, from forked repo

---

bluemira/geometry/parameterisations.py
bluemira/geometry/tools.py
bluemira/magnetostatics/baseclass.py
bluemira/magnetostatics/biot_savart.py
bluemira/magnetostatics/circuits.py
bluemira/magnetostatics/circular_arc.py
bluemira/magnetostatics/polyhedral_prism.py
bluemira/magnetostatics/trapezoidal_prism.py
bluemira/utilities/opt_variables.py

Issue #3022 on fixing typing in codebase

Papercut typing fixes #3022 jmatthews

---

pyproject.toml
requirements.txt

Use numba scipy version instead of git hash 

⬆️ Bump numba-scipy from 1e2f224 to 0.4.0

---

bluemira/equilibria/coils/_coil.py
bluemira/equilibria/find.py
bluemira/equilibria/plasma.py
bluemira/magnetostatics/semianalytic_2d.py

Fixes some of the warnings introduced in the py3.8->py3.10 migration

🚨 Reduce warnings in tests

---

.github/workflows/actions/build/action.yml
.github/workflows/release.yml

Its boolean not bool for the input type variables
https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-inputs-context-in-a-manually-triggered-workflow
None 

🐛 Bool -> boolean in CI

---

bluemira/plasma_physics/collisions.py
bluemira/plasma_physics/rules_of_thumb.py

Corrected a.m.u. back into e

---

bluemira/base/reactor.py
bluemira/materials/cache.py
bluemira/materials/constants.py
bluemira/materials/material.py
bluemira/materials/mixtures.py
bluemira/materials/tools.py
bluemira/utilities/tools.py
data/materials/materials.json
data/materials/mixtures.json
documentation/source/materials/materials.rst
examples/materials/material_definitions.ex.py
pyproject.toml
requirements.txt
tests/materials/test_material.py
tests/materials/test_mixtures.py

Moves materials work from neutronics feature branch to develop

Move materials changes from neutronics feature branch

---

README.md
documentation/source/bluemira-roadmap-dark.svg
documentation/source/bluemira-roadmap.svg
documentation/source/introduction.rst

Roadmap update for the next quarter

📝 Roadmap update

---

.github/workflows/comments.yml
.github/workflows/examples.yml
bluemira/balance_of_plant/steady_state.py
bluemira/base/logs.py
bluemira/base/look_and_feel.py
bluemira/base/parameter_frame/_frame.py
bluemira/builders/tf_coils.py
bluemira/equilibria/coils/_field.py
bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
bluemira/equilibria/optimisation/problem/_nested_position.py
examples/codes/run_process_example.ex.py

Minor fixes in examples and docs 

🩹 Pre release minor fixes

---

bluemira/radiation_transport/advective_transport.py
bluemira/radiation_transport/flux_surfaces_maker.py
tests/radiation_transport/test_advective_transport.py

Remove duplicate flux surface code from radiation_transport

---

bluemira/codes/openmc/output.py
bluemira/codes/openmc/solver.py
bluemira/codes/openmc/tallying.py
bluemira/codes/wrapper.py
eudemo/eudemo/neutronics/run.py

Adds default tallies to neutronics run

Improve tallies

---

bluemira/display/palettes.py
bluemira/equilibria/coils/_grouping.py
bluemira/equilibria/equilibrium.py
bluemira/equilibria/file.py
bluemira/equilibria/grid.py
bluemira/equilibria/profiles.py
bluemira/geometry/coordinates.py
bluemira/geometry/tools.py
bluemira/utilities/tools.py
tests/geometry/test_coordinates.py

Typing fixes

---

.github/workflows/release.yml

👷 Fix make release

---

.github/workflows/dependencies_pr.yml

👷 Fix dependencies PR ci

---

bluemira/display/plotter.py

added hatch plot opt to FacePlotter

---

bluemira/radiation_transport/advective_transport.py
tests/radiation_transport/test_advective_transport.py

Closes #870 
Renames variables to separate low field side/ high field side, upper div/lower div and inboard/outboard.
See https://doi.org/10.1109/TPS.2024.3390413 figure 1 for a good example of the layout meanings
Variable name changes in the class as specified above

🎨 Clearer naming wrt ib/ob, upper/lower and hfs/lfs

---

tests/radiation_transport/test_radiation_profile.py
tests/radiation_transport/test_radiation_tools.py

#3212 #3328 #3330
Moved some tests from test_radiation_profiles to test_radiation_tools. Added test for radiative_loss_function_values.

Adding more unit tests to radiation source model

---

tests/radiation_transport/test_advective_transport.py

Closes #3329 
Adds tests to complete coverage of advective transport.

Tests for advective transport in radiation transport

---

.github/workflows/ci.yml

Upload artifacts v4

---

bluemira/equilibria/plotting.py
bluemira/utilities/plot_tools.py

Smooths the edge of the plasma current filled contour for the lcfs, before and after
None

🎨 Smooth filled contour edges for LCFS

---

bluemira/codes/_freecadapi.py
bluemira/geometry/tools.py
tests/geometry/test_sweep.py

Add loft to geometry tools through the freecad api

✨ Add loft to freecadapi and geometry

---

tests/radiation_transport/test_radiation_profile.py

Add more tests for radiation source model 

---

.github/workflows/actions/dependencies_PR/action.yml

Attempts to fix dependency PR creation

👷 Fix dependency PR CI

---

eudemo/config/build_config.json
eudemo/eudemo/model_managers.py
eudemo/eudemo/neutronics/run.py
eudemo/eudemo/pf_coils/designer.py
eudemo/eudemo/reactor.py

Initial neutronics manager, for now just stores stuff and allows plotting of openmc figure

✨ Add Neutronics Manager to eudemo

---

bluemira/balance_of_plant/plotting.py
bluemira/balance_of_plant/steady_state.py
bluemira/base/builder.py
bluemira/base/components.py
bluemira/base/designer.py
bluemira/base/parameter_frame/_frame.py
bluemira/base/parameter_frame/typing.py
bluemira/base/reactor.py
bluemira/base/reactor_config.py
bluemira/builders/coil_supports.py
bluemira/builders/cryostat.py
bluemira/builders/divertor.py
bluemira/builders/pf_coil.py
bluemira/builders/plasma.py
bluemira/builders/radiation_shield.py
bluemira/builders/tf_coils.py
bluemira/builders/thermal_shield.py
bluemira/builders/tools.py
bluemira/display/plotter.py
bluemira/equilibria/equilibrium.py
bluemira/equilibria/plotting.py
bluemira/geometry/base.py
bluemira/geometry/face.py
bluemira/geometry/tools.py
bluemira/geometry/wire.py

#3022 
More type changes. Addition of TypeVar, using some inspiration from https://rogulski.it/blog/python-typing-with-generic-typevar/
Users should use the new types `ParameterFrameLike`, `ParameterFrameT` and `ConstraintT` where appropriate

🏷️ More typing improvements

---

bluemira/base/logs.py
bluemira/geometry/tools.py
tests/geometry/test_tools.py

If bluemira is installed to site-packages this folder wont exist therefore we make one in the cwd if required.

🐛 Catch debug folder path doesnt exist

---

bluemira/radiation_transport/flux_surfaces_maker.py
tests/radiation_transport/test_flux_surface_maker.py

add some tests for flux surface maker

---

bluemira/radiation_transport/flux_surfaces_maker.py
bluemira/radiation_transport/radiation_profile.py
bluemira/radiation_transport/radiation_tools.py

Few changes to correct the radiation region extention

---

.github/workflows/documentation-preview.yml
documentation/source/base/design_build.dot

The image links in the intro were 1 level too deep

🐛 Fix image links in introduction

---

bluemira/base/reactor.py

FilterMaterial typing fix

---

bluemira/base/logs.py
tests/base/test_look_and_feel.py

Fixes odd newlines when we transition from progress like logging to normal messages

🐛 Log newlines when needed

---

bluemira/geometry/optimisation/typing.py

Geom opt typing

---

tests/radiation_transport/test_radiation_profile.py

🐛 Fix sonarcloud quality bug

---

bluemira/base/logs.py

I broke the logging setup in #3430 

🐛 Fix logging setup

---

bluemira/equilibria/optimisation/constraint_funcs.py

Papercut #1107
Separate coil force constraint equations.  

Split out force constraint calculations into separate functions

---

bluemira/codes/_freecadapi.py
bluemira/geometry/tools.py

🎨 Add loft arg

---

documentation/source/developer/faq.rst

Closes #3452 
----
📚 Documentation preview 📚: https://bluemira--3489.org.readthedocs.build/en/3489/

add how to render docs locally to faq section of docs

---

bluemira/equilibria/profiles.py

hotfix: Custom Profiles, added abs() to B_0, I_p

---

bluemira/structural/constants.py
bluemira/structural/crosssection.py
bluemira/structural/element.py
bluemira/structural/geometry.py
bluemira/structural/loads.py
bluemira/structural/model.py
bluemira/structural/node.py
bluemira/structural/plotting.py
bluemira/structural/result.py
bluemira/structural/symmetry.py
tests/structural/test_loads.py

Enums, dataclasses and not inheriting from list

🎨 Structural cleanup

---

.github/workflows/actions/process/action.yml
.github/workflows/ci.yml
tests/radiation_transport/test_radiation_profile.py

✨ Install process in CI

---

bluemira/radiation_transport/radiation_tools.py
tests/radiation_transport/test_radiation_profile.py

Improve wall detector structure #3437 (Papercut)

---

eudemo/eudemo/equilibria/_designer.py
eudemo/eudemo/pf_coils/designer.py

Equ read eqdsk fixes

---

bluemira/fuel_cycle/cycle.py

In #3487 I reversed the sign of this check which is not logically the same as the previous version. this is

🐛 Wrong sign for check

---

bluemira/equilibria/coils/_coil.py
bluemira/equilibria/coils/_field.py
bluemira/equilibria/coils/_grouping.py
bluemira/equilibria/equilibrium.py
bluemira/magnetostatics/semianalytic_2d.py
tests/equilibria/test_coils.py

Closes #191 
Threads in the semi analytic psi function into the coil field calculations, and some cleanup of unneeded functions.
This should be thoroughly benchmarked before merge.

Thread in semianalytic psi into coil calculations

---

bluemira/base/logs.py

Logging is now directed to stderr or stdout dependent on log level

✨ INFO and greater to stdout WARNING and less to stderr

---

tests/magnetostatics/test_greens.py

Makes sure we compare the two greens functions and that they produce the same result

✅ Extra greens test

---

.github/workflows/dependabot_helper.yml

Adds a CI helper to update requirements files after dependabot opens a PR

👷 Add dependabot helper CI

---

bluemira/geometry/_pyclipper_offset.py
bluemira/geometry/base.py
bluemira/geometry/bound_box.py
bluemira/geometry/compound.py
bluemira/geometry/coordinates.py
bluemira/geometry/face.py
bluemira/geometry/optimisation/_optimise.py
bluemira/geometry/optimisation/_tools.py
bluemira/geometry/optimisation/problem.py
bluemira/geometry/parameterisations.py
bluemira/geometry/placement.py
bluemira/geometry/plane.py
bluemira/geometry/shell.py
bluemira/geometry/solid.py
bluemira/geometry/tools.py
bluemira/geometry/wire.py
pyproject.toml

Geometry DOC201

---

bluemira/display/auto_config.py
bluemira/display/displayer.py
bluemira/display/palettes.py
bluemira/display/plotter.py
bluemira/display/tools.py
bluemira/optimisation/_algorithm.py
bluemira/optimisation/_nlopt/conditions.py
bluemira/optimisation/_nlopt/functions.py
bluemira/optimisation/_nlopt/optimiser.py
bluemira/optimisation/_optimise.py
bluemira/optimisation/_tools.py
bluemira/optimisation/problem.py
pyproject.toml

Doc201 optimisation display

---

conftest.py
documentation/source/equilibria/equilibria.rst

Closes #3361 
----
📚 Documentation preview 📚: https://bluemira--3523.org.readthedocs.build/en/3523/

Updated docs to describe Circuits and SymmetricCircuits

---

tests/radiation_transport/test_radiation_profile.py

Add more radiation transport tests

---

bluemira/magnetostatics/baseclass.py
bluemira/magnetostatics/biot_savart.py
bluemira/magnetostatics/circuits.py
bluemira/magnetostatics/circular_arc.py
bluemira/magnetostatics/fem_utils.py
bluemira/plasma_physics/collisions.py
bluemira/plasma_physics/reactions.py
bluemira/plasma_physics/rules_of_thumb.py
bluemira/plasma_physics/scaling_laws.py
pyproject.toml

Plasma Physics and partial coverage of Magnetostatics

---

bluemira/radiation_transport/advective_transport.py
tests/radiation_transport/test_advective_transport.py

Fixing heat flux corrective factor

---

bluemira/magnetostatics/circuits.py
bluemira/magnetostatics/fem_utils.py
bluemira/magnetostatics/finite_element_2d.py
bluemira/magnetostatics/greens.py
bluemira/magnetostatics/polyhedral_prism.py
bluemira/magnetostatics/semianalytic_2d.py
bluemira/magnetostatics/tools.py
bluemira/magnetostatics/trapezoidal_prism.py
pyproject.toml

#3504
----
📚 Documentation preview 📚: https://bluemira--3602.org.readthedocs.build/en/3602/

Doc201 remainder of magnetostatics

---

bluemira/equilibria/physics.py
bluemira/materials/material.py
bluemira/plasma_physics/rules_of_thumb.py

Add to/check for equations and references in docstrings 

---

bluemira/radiation_transport/radiation_tools.py

Already referenced in docs but now use full reference in function docstring - #1043

Possibly the tiniest merge request so far 

---

bluemira/radiation_transport/advective_transport.py

When fixing #3557, it was not added for the double null case the possibility of having only one intersection point in the region in proximity of the mid-plane.

Fix charged particle heat flux calculation for double null case with only one mid-plane point

---

.gitignore

Ignores tmp_env.yml that is created on environment install for specific python versions

add tmp_env.yml to .gitignore

---

bluemira/codes/_freecadapi.py
bluemira/geometry/tools.py

Closes #3571
Relaxes some typing constraints to make geometry/tools.py easier to.

🎨 Relax interface to geometry tools

---

conda/miniforge-init.sh

Missed some mambaforge entries

🐛 Fix miniforge init script

---

eudemo/eudemo/reactor.py

Demo syntax error because component managers have slightly changed

🐛 Fix demo bug

---

bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py

Use coilset.control rather coilset.name in the check coils part of the spherical harmonic approximation. 

Control coils missing

---

.readthedocs.yaml
documentation/source/installation.rst
scripts/install-process.sh

Closes #3631 
Removes a few missed refs to mambaforge and fixes a warning in the process install script
----
📚 Documentation preview 📚: https://bluemira--3632.org.readthedocs.build/en/3632/

Remove old mambaforge references

---

bluemira/display/plotter.py
bluemira/geometry/coordinates.py
bluemira/geometry/face.py
bluemira/utilities/tools.py

Closes #3574 
Cleans up some plotting and moves the cadapi use into BluemiraFace (the second commit is the actual fix)

Fix display todo for faces

---

bluemira/base/parameter_frame/_frame.py
bluemira/codes/process/_teardown.py
bluemira/codes/process/api.py
eudemo/config/params.json
eudemo/eudemo/neutronics/run.py

🎨 Add sources to sourceless input params

---

.github/workflows/examples.yml
scripts/install-conda.sh

another miss🤦‍♂️

---

pyproject.toml

Eqdsk has some api changes on 0.5 so the next release

📌 Max pin on eqdsk

---

bluemira/equilibria/find_legs.py

Add check as we are assuming mid plane

---

bluemira/equilibria/grid.py
tests/equilibria/test_grid.py

Error found for grid z_range, added and tested suggested correction

---

scripts/install-conda.sh

Improves the install script allowing for use with the template repo

🎨 Improve install script

---

.github/workflows/ci.yml
.github/workflows/comments.yml

CI report comments fix

---

.github/workflows/comments.yml

Changed comments workflow to pickup new test-report.json

---

eudemo/eudemo/equilibria/_designer.py

🐛 Missed EQSummary use

---

bluemira/equilibria/fem_fixed_boundary/utilities.py
bluemira/magnetostatics/fem_utils.py
bluemira/magnetostatics/finite_element_2d.py
tests/equilibria/fem_fixed_boundary/test_fem_utils.py

Updates fenicsx, needed for #3304 

⬆️ Update fenicsx to v 0.9

---

.github/workflows/examples.yml

👷 Fix examples CI

---

.github/workflows/actions/build/action.yml

Closes #{ID}
Removes some CI warnings

👷 Remove CI warning

---

tests/equilibria/test_constraint_functions.py
tests/equilibria/test_constraints.py

Papercut add control coil test

---

bluemira/equilibria/coils/_field.py
bluemira/equilibria/coils/_tools.py
bluemira/geometry/coordinates.py
bluemira/materials/mixtures.py
bluemira/radiation_transport/radiation_tools.py

Addresses #1043 
As of the latest commit, added docstring to few functions in

Add Equations/References in docstring : Sprint 22

---

bluemira/equilibria/coils/_grouping.py
tests/equilibria/test_coils.py

Added nested coil remove test

---

bluemira/equilibria/find_legs.py

Need x_p in get_single_null_legs, cannot be None.

---

bluemira/fuel_cycle/lifecycle.py
bluemira/fuel_cycle/timeline.py
bluemira/fuel_cycle/timeline_tools.py
bluemira/utilities/tools.py
examples/fuel_cycle/EUDEMO_fuelcycle.ex.py
tests/fuel_cycle/test_tools.py

Implementation of #3735 that aims to be both random and deterministic

🎨 Make fuel cycle model random and deterministic

---

bluemira/display/plotter.py
conftest.py
tests/_helpers.py
tests/base/test_file.py
tests/base/test_look_and_feel.py
tests/base/test_reactor.py
tests/codes/plasmod/test_solver.py
tests/display/test_plotter.py
tests/equilibria/fem_fixed_boundary/test_Solovev.py
tests/equilibria/fem_fixed_boundary/test_fem_magnetostatic_2D.py
tests/equilibria/test_optimisation.py
tests/radiation_transport/test_advective_transport.py
tests/structural/test_crosssection.py

Automatically adds a title to figures in tests so they can be tracked down if there is something wrong.
Only works if 'show' is not called within the test

Add titles to all test plots

---

.readthedocs.yaml

Closes #{ID}
Read the docs now enforces explicit path to conf.py
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

👽️ Fix sphinx build

---

bluemira/equilibria/optimisation/constraint_funcs.py
tests/equilibria/test_constraint_functions.py

Closes #3035 - > field and force constraints modified and now tested using 'approx_derivative'.

Coil Field and Force Constraints Grad Modification

---

bluemira/base/reactor.py
tests/base/test_reactor.py

Closes #{ID}
Returns the ability to specify certain parameters for showing and saving in component managers and reactor objects

🚑️ Unbreak show/save/plot reactor apis

---

bluemira/base/tools.py

Added  disable_composite_grouping

---

requirements/conda.txt

Closes #{ID}
CI was failing because different pyside now pulled in

💚 Fix conda build

---

requirements/conda.txt

The pyside pinning doesnt gain us anything other than version knowledge so unpinning

💚 Unpin pyside

---

.pre-commit-config.yaml

As prettier pre-commit is archived moving to biome, they dont yet support yaml so leaving that for now
None

🚨 Use biome for json files

---

bluemira/radiation_transport/radiation_profile.py
bluemira/radiation_transport/radiation_tools.py
tests/radiation_transport/test_radiation_profile.py

Closes #3330  
Closes #3212 
Papercut for adding more tests to radiation_tools.py.
Some functions aren't tested (see #3330). Issue #3328  is not fully solved as test data for single-null tokamak is required.
N/A

Finalising tests to radiation_transport

---

bluemira/structural/element.py
bluemira/structural/node.py

Addresses #1043 
Added docstrings for few functions in elements and nodes

Papercut: Smallest PR adding physics/equation docstring

---

conda/environment.yml
requirements/conda.txt

This fixes some of our conda issues around changing dependencies. Curretly fixes a h5py upgrade

🐛 Fix h5py in conda build

---

bluemira/base/parameter_frame/_frame.py
tests/base/parameterframe/test_parameterframe.py

Add unit compatibility check in ParameterFrame._set_param

---

.github/workflows/ci.yml
conda/environment.yml

FreeCAD now has a python 3.12 image on conda-forge allowing us to upgrade our supported version

⬆️ Enable python-3.12

---

.github/workflows/actions/dependencies_PR/action.yml

Closes #3817 
The force push doesnt seem to work on the action when there is any change. Therefore removing. We can always rebase manually.

🔥 Remove rebase from dependency PR action

---

bluemira/base/logs.py

We just want to increase the stacklevel shown not override it completely

🐛 Stack level fix, dont override, add to

---

.github/workflows/ci.yml

Puts the precommit output into the Ci job summary:
See:
https://github.com/Fusion-Power-Plant-Framework/bluemira/actions/runs/14246180848

👷 Print pre-commit summary to github summary

---

bluemira/geometry/tools.py

Add missing space in geometry warning

---

bluemira/base/reactor.py
bluemira/base/tools.py
bluemira/builders/coil_supports.py
bluemira/builders/tf_coils.py
bluemira/codes/_freecadapi.py
bluemira/display/displayer.py
bluemira/equilibria/analysis.py
bluemira/equilibria/equilibrium.py
bluemira/equilibria/find.py
bluemira/equilibria/flux_surfaces.py
bluemira/equilibria/profiles.py
bluemira/equilibria/solve.py
eudemo/eudemo/ivc/wall_silhouette.py
tests/equilibria/test_equilibrium.py
tests/equilibria/test_st_equilibrium.py

Various minor bugfixes found when rebasing various reactor studies

Various minor bugfixes 

---

bluemira/codes/process/mapping.py
bluemira/codes/process/params.py
tests/codes/process/test_data/params.json

Add some CS output mappings from PROCESS

---

eudemo/eudemo/pf_coils/designer.py

Add docstrings for the pf_coil parameter frame in eudemo

---

bluemira/base/parameter_frame/__init__.py
bluemira/base/parameter_frame/_frame.py
bluemira/equilibria/analysis.py
bluemira/equilibria/flux_surfaces.py
bluemira/equilibria/physics.py
bluemira/equilibria/plotting.py
bluemira/utilities/tools.py
eudemo/eudemo/equilibria/_designer.py
tests/equilibria/test_analysis.py

🖌️ Improve structure of some eq analysis tools

---

bluemira/equilibria/find.py
bluemira/utilities/tools.py
tests/base/test_look_and_feel.py
tests/codes/plasmod/test_solver.py
tests/equilibria/test_coils.py
tests/geometry/test_coordinates.py
tests/geometry/test_geometry.py
tests/materials/test_material.py
tests/radiation_transport/test_advective_transport.py
tests/structural/test_geometry.py

Closes #3878 
Some of our tests hold state that is mutable. This is bad and leads to randomly failing tests.
Here I've fixed a few of them that I can find.
Used the `pytest-randomly` package to find these

Temperamental test fixes

---

eudemo/eudemo/equilibria/_designer.py

Added .value to plasma_data params

---

bluemira/optimisation/_nlopt/optimiser.py
tests/optimisation/test_nlopt.py

Papercut: optimiser warning if arrive at max iter

---

tests/optimisation/geometry/test_geometry.py

Remove todo re. keeping geom param constant

---

bluemira/codes/openmc/output.py
bluemira/codes/openmc/tallying.py

Add neutronics outputs

---

.github/workflows/dependabot_helper.yml

Checks pyproject toml and adds any new dependency to the requirements files
still effected by #3755

Check pyproject changes for dependency addition

---

bluemira/equilibria/find_legs.py
bluemira/geometry/coordinates.py

Closes #3585 
Cleanup 2 might be coming from solving issue #3926 
Removed the TODO, and tidied up some of the functions by adding docs & renaming internal variables.
I happen to also have added docstrings on equilibria/find_legs.py
N/A

join_intersect cleanup 1

---

bluemira/equilibria/find_legs.py
bluemira/equilibria/flux_surfaces.py
bluemira/geometry/coordinates.py
tests/geometry/test_coordinates.py

Closes #3926 
Changed the signature of join_intersect.
join_intersect has been changed. But looks like no end-user will see/use this function directly.

Functionalised join_intersect.

---

bluemira/codes/cgal_ext/collision_detection.py
bluemira/codes/python_occ/imprintable_solid.py

Fix: error on importing types from cgal and OCC

---

.github/workflows/dependabot_helper.yml

Stop running dependencies ci jobs on forks

🐛 Fix not running on fork

---

eudemo/eudemo/radial_build.py
examples/codes/run_process_example.ex.py

🎨 Missed max_iterations -> maxiter

---

bluemira/codes/python_occ/imprint_solids.py
bluemira/utilities/tools.py

Post #3916 merge
This reduces some logging output and makes sure the imprinter doesnt start if there is nothing to do

🎨 Small change to imprinting

---

examples/equilibria/quick_look_at_example_coilsets.ex.py

🐛 Fix examples again

---

bluemira/equilibria/analysis.py
bluemira/equilibria/diagnostics.py
bluemira/equilibria/equilibrium.py
bluemira/equilibria/find_legs.py
bluemira/equilibria/flux_surfaces.py
bluemira/equilibria/optimisation/problem/_tikhonov.py
bluemira/equilibria/optimisation/problem/base.py
bluemira/equilibria/plotting.py
bluemira/equilibria/profiles.py
bluemira/equilibria/shapes.py
bluemira/geometry/optimisation/_optimise.py
bluemira/geometry/parameterisations.py
bluemira/optimisation/_optimise.py
bluemira/optimisation/_optimiser.py
bluemira/optimisation/problem.py
bluemira/plasma_physics/rules_of_thumb.py
bluemira/radiation_transport/radiation_profile.py
bluemira/radiation_transport/radiation_tools.py
examples/equilibria/Spherical_Approximation_how_it_works.ex.py
examples/equilibria/spherical_harmonic_approximation_basic_use.ex.py

Closes #3879 
Remove spelling errors (or change from US to UK spelling). 

Remove spelling errors in bulk.

---

bluemira/materials/material.py
bluemira/radiation_transport/radiation_profile.py

Fix some bugs sonarcloud found 
https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&types=BUG&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&inNewCodePeriod=true&sinceLeakPeriod=true&id=Fusion-Power-Plant-Framework_bluemira

🐛 Fix sonarcloud codeqa

---

bluemira/builders/tf_coils.py
bluemira/geometry/optimisation/_tools.py
eudemo/eudemo/blanket/panelling/_opt_problem.py
eudemo/eudemo/maintenance/upper_port.py
examples/design/simple_reactor.ex.py
examples/optimisation/geometry_optimisation.ex.py

This names a few more of our hard coded constraints to aid in diagnostics

🎨 Name more constraints

---

.github/workflows/ci.yml

Cache's precommit so install of hooks can be loaded from cache

👷 Cache precommit

---

.pre-commit-config.yaml

| Before      | After      |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/fae1f8c4-e64c-46c7-bd19-dfcc18169adb) | ![image](https://github.com/user-attachments/assets/f852c241-a43f-4eb6-9466-dbe74b32eae7) |

👷 Update ruff check alias

---

bluemira/equilibria/analysis.py
bluemira/equilibria/coils/_field.py
bluemira/equilibria/coils/_grouping.py
bluemira/equilibria/coils/_tools.py
bluemira/equilibria/equilibrium.py
bluemira/equilibria/flux_surfaces.py
bluemira/equilibria/grid.py
bluemira/equilibria/profiles.py
bluemira/equilibria/solve.py
bluemira/magnetostatics/fem_utils.py
bluemira/radiation_transport/flux_surfaces_maker.py
bluemira/radiation_transport/radiation_profile.py
bluemira/radiation_transport/radiation_tools.py

part of #3022 
Using ty to improve some types

🏷️ Typing improvements from ty

---

bluemira/radiation_transport/neutronics/blanket_data.py

Confirmation of KALOS-ACB packing fraction

---

bluemira/radiation_transport/radiation_tools.py

More information added to radiation tools docstrings

---

bluemira/radiation_transport/radiation_tools.py

Papercut: comment on ```detected_power``` calculation

---

bluemira/geometry/coordinates.py
documentation/source/fuel_cycle/fuel_cycle.rst

Fixes link
----
📚 Documentation preview 📚: https://bluemira--4027.org.readthedocs.build/en/4027/

Fix doc links

---

.github/workflows/actions/build/action.yml
.github/workflows/ci.yml
.github/workflows/examples.yml

Our conda and pip build step caches are not being saved properly this fixes the problem

👷 Fix build caching

---

bluemira/magnets/fatigue.py
documentation/source/examples.rst
tests/magnets/test_fatigue.py

CS magnet fatigue model

---

.github/workflows/dependabot_helper.yml

Closes #{ID}
Missed one in #3698 

👷 Dependabot sonarcloud

---

bluemira/equilibria/equilibrium.py
bluemira/equilibria/find.py
bluemira/equilibria/plotting.py
bluemira/equilibria/profiles.py
bluemira/equilibria/run.py
bluemira/equilibria/solve.py
eudemo/eudemo/equilibria/_designer.py
eudemo/eudemo/equilibria/_equilibrium.py
tests/equilibria/test_equilibrium.py

Closes #3583 
Adds the suggested o point fallback 
Addition of 'o_point_fallback' kwarg
TODO:

✨ Add o-point fallback options

---

bluemira/equilibria/diagnostics.py
bluemira/equilibria/solve.py
bluemira/utilities/plot_tools.py

Fixed some problems plotting and saving figures
New file format key in diagnostic plotting

🐛 Fix gif saving and plotting
