Fusion-Power-Plant-Framework/bluemira

- .github/workflows/ci.yml
Closes #539 
Adds an upload to Codecov of the coverage.xml file produced by the bluemira tests to our CI job. Also switches on the reactor tests for bluemira.
N/A
> Add CI step to upload coverage to Codecov

- examples/geometry/geometry_tutorial.ipynb
- examples/geometry/geometry_tutorial.py
Supersedes #542 
This PR converts our geometry tutorial to a Jupyter notebook and adds simple plotting functionality into that tutorial.
N/A
> Convert geometry tutorial to jupyter and add plotting

- bluemira/codes/interface.py
- tests/bluemira/codes/test_interface.py
Realised its possible to craft a dict like object that ignores pop. This will now error with two arguments specified if someone tries this. I think we're protected by kwargs anyway but best to be safe.
```python
In [9]: d
Out[9]: {'a': 1}
In [10]: class CustomDict(dict):
...:    def __init__(self,*arg,**kw):
...:       super().__init__(*arg, **kw)
...:    def pop(self, *args, **kw):
...:        pass
...: 
In [11]: d = CustomDict({'a':1})
In [12]: d.pop('a')
In [13]: d
Out[13]: {'a': 1}
```
> 🐛 further protect subprocess

- bluemira/base/components.py
- bluemira/builders/EUDEMO/plasma.py
- bluemira/builders/plasma.py
- bluemira/display/__init__.py
- bluemira/display/displayer.py
- bluemira/display/plotter.py
- bluemira/geometry/__init__.py
- bluemira/geometry/plotting.py
- bluemira/geometry/tools.py
- bluemira/materials/__init__.py
- bluemira/materials/cache.py
- bluemira/materials/error.py
- bluemira/materials/material.py
- bluemira/materials/mixtures.py
- bluemira/radiation_transport/__init__.py
Hopefully Closes #533 
Attempt to deal with circular imports
flake8 fails because it cant find some annotations as imports
> Circular imports

- bluemira/base/__init__.py
When in ipython and trying to directly import `bluemira.utilities.tools` it moans about circular imports. If I import `bluemira.base` first it doesnt moan. This makes it so the import always works. In my head the imports are the same (and locals tells me that). Don't really get it...
> 🐛 Fix weird circular import

- bluemira/utilities/tools.py
- tests/bluemira/utilities/test_tools.py
Our module loader only worked if the file extension was '.py' and a python file, now it works with any extension if python can import it.
> Load anything

- tests/bluemira/builders/test_shapes.py
We are occasionally getting failures in `test_shapes.py` (ranging from 1-2, depending on luck).
Fixes above failures by adding an `ftol_rel` termination condition to the optimiser. Previously, not setting this was meaning that the optimisation algorithm would terminate after `max_eval` leading to potential round-off error failures.
N/A
> Fix intermittent failures in `test_shapes.py`

- tests/bluemira/builders/EUDEMO/test_reactor.py
test_reactor test_plasma_build very sensitive to changes in equilibria requiring rebaselining frequently
This PR replaces the test with a less strict comparison of equilibria based on the LCFS.
N/A
> Replace plasma test in `test_reactor.py` 

- BLUEPRINT/systems/firstwall.py
- tests/BLUEPRINT/systems/test_firstwall.py
#432 
In some cases, depending on the target type (horizontal or vertical), the plasma flux region side and the scrape off layer side of the target appeared to be swapped.
Now it should work. Sorry @sebkahn, I didn't find any more elegant way.
> Divertor target swap

- bluemira/builders/EUDEMO/pf_coils.py
- bluemira/codes/_freecadapi.py
- bluemira/geometry/tools.py
- bluemira/utilities/positioning.py
- tests/bluemira/builders/EUDEMO/test_pf_coils.py
- tests/bluemira/geometry/test_tools.py
Adds a track decomposition tool for placing PF coils along a wire based on exclusion zones and a set of coils.
Adds support to `distance_to` to handle points
Adds `point_inside_shape` because I thought I needed it for this... Note that the FreeCAD version seems much less accurate on a 2-D shape than previous discretised methods.
`distance_to` can now handle iterables of length 3 and treat them as points
> Add track tool for PF coil positioning

- bluemira/utilities/plot_tools.py
N/A
The last couple of tests in tests/bluemira/geometry/test_deprecated_loop.py fail if run with --plotting-on. This is because of an import that hasn't been updated to use the new `coordinate` functionality. This PR fixes that.
N/A
> Fix plotting test

- BLUEPRINT/systems/firstwall.py
Closes https://github.com/Fusion-Power-Plant-Framework/bluemira/issues/610
Related STEP issues:
- STEP Merge request depending on this issue: https://git.ccfe.ac.uk/step-bluemira-reactor-design/step-blueprint-reactor-design/-/merge_requests/84/edit
Quick-fixes the FW failure. Removing the second call for `make_2d_profile()` in `FirstWall` `build()` function. The failure happening for the second call.
The second call was itended to allow the drawing of the flux line in the divertor region. The FW region flux lines seems not to need this feature anymore to show the dinvertor regions flux line to my amazement.
> Removing the seconf `make_2d_profie` call

- documentation/source/installation.rst
Closes #604 
Adds installation of `gcc` and `make` to the PROCESS installation documentation. 
> Add PROCESS build dependencies to installation guide

- bluemira/base/design.py
- examples/design/design_shapes.ipynb
- examples/design/design_shapes.py
- tests/bluemira/base/test_design.py
N/A
The component tree for the design_shape example was failing as the Design was being defined without a name. This PR looks to ensure that generic Designs are defined with all of the required parameters in place (most are handled by the validation on the resulting Builder classes). It adds the Name parameter to the example design, and converts the example to a Jupyter notebook.
Validation added to ensure required parameters are provided to a design.
> Shape design parameter validation and notebook conversion

- bluemira/codes/process/run.py
- bluemira/codes/process/teardown.py
- tests/bluemira/codes/process/test_run.py
This allows access directly to the mfile data from the process solver object if parameters are not mapped. 
At the same time I've simplified a bit of logic for loading mfiles contents
All mfile variables are now accessible
> 🎨 uplift process mfile interface

- bluemira/base/parameter.py
- bluemira/codes/utilities.py
- tests/BLUEPRINT/cli/test_indir/SMOKE-TEST_template.json
Closes #532 
Default mapping is now a dictionary converted inside parameter
No longer need to protect against None for parameter.mapping
> 🎨 default mapping

- bluemira/geometry/parameterisations.py
- bluemira/utilities/opt_variables.py
- tests/bluemira/geometry/test_parameterisations.py
- tests/bluemira/utilities/test_opt_variables.py
Closes #621 
Implements serialisation for `OptVariables` and applies it to `GeometryParameterisation` classes.
Adds `to_json` and `from_json` to `OptVariables` and `GeometryParameterisation` classes.
> Serialisation for GeometryParameterisations

- bluemira/builders/EUDEMO/reactor.py
- bluemira/builders/EUDEMO/tf_coils.py
- bluemira/builders/shapes.py
- data/reactors/EU-DEMO/geometry/tf_coils_TripleArc_18.json
- examples/design/EU-DEMO/EUDEMO_reactor.ipynb
- examples/design/EU-DEMO/EUDEMO_reactor.py
- tests/bluemira/builders/EUDEMO/test_data/tf_coils_TripleArc_18.json
- tests/bluemira/builders/EUDEMO/test_reactor.py
- tests/bluemira/builders/EUDEMO/test_tf_coils.py
- tests/bluemira/builders/test_shapes.py
N/A
This PR supports saving the TF Coils builder shape (and any other shape builders) to a json file.
Adds `save_shape` to `ParameterisedShapeBuilder`.
> Save TF Shape

- .github/ISSUE_TEMPLATE/eu_demo_feature_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/step_feature_request.md
N/A
Fixes typos in the GitHub issue templates.
> Fix typos in GitHub issue templates

- bluemira/display/plotter.py
- tests/bluemira/display/test_plotter.py
N/A
When providing an axis to `plot_3d`, this wasn't being passed through into the initialisation of the plot. This PR ensures that the axis is always provided to `initialize_plot_3d`.
None
> Pass axis to plot_3d if specified

- bluemira/equilibria/equilibrium.py
Without this the eqdsk writer sometimes crashes
N/A
> 🐛 safety factor an array or float not list

- bluemira/equilibria/coils.py
- tests/bluemira/equilibria/test_coils.py
Closes #655.
This changes the way coils are sorted in the `CoilGroup.sort_coils` method. Previously they were sorted into alphabetical order, which naively meant that numbers in strings were sorted based on their leading digit. This has now been changed so that any numbers present in the string will be sorted according to their numerical value. This is a so-called "natural sort order".
None.
> Implement "natural order sort" in for coil names in CoilGroup

- bluemira/base/builder.py
- bluemira/base/design.py
- bluemira/builders/EUDEMO/plasma.py
- bluemira/builders/EUDEMO/reactor.py
- bluemira/builders/EUDEMO/tf_coils.py
- bluemira/builders/plasma.py
- bluemira/builders/shapes.py
- examples/design/design_plasma.ipynb
- examples/design/design_plasma.py
- tests/bluemira/builders/EUDEMO/test_tf_coils.py
- tests/bluemira/builders/test_plasma.py
- tests/bluemira/builders/test_shapes.py
Related to #629 
This moves various kwargs usage, which is currently prevalent in many function signatures, to the init function. In this way, each builder can be set up and reinitialised as required, but is always called the same way. The usage of explicit arguments on the implementations of the init functions for concrete classes should also make it easier to follow what arguments need to be passed in.
The `Builder` classes now setup everything that they need in `__init__` and `reinitialise`. This means that the `build` and runmodes (`run`/`read`/`mock`) are called consistently without any arguments. The `_build_stage` in `Reactor` is now also called without arguments. `kwargs` are removed from places where they are not longer used.
> Move arguments to init

- bluemira/materials/constants.py
- bluemira/materials/material.py
- bluemira/materials/mixtures.py
- tests/bluemira/materials/test_mixtures.py
Closes #627 
Remove the `make_mat_dict` method from `Material` - to be implemented in the new structural module.
Remove the `make_mat_dict` method from `Material`
> Remove all traces of `beams` module from `materials`.

- bluemira/base/parameter.py
- bluemira/codes/interface.py
- examples/codes/run_plasmod_example.ipynb
- examples/codes/run_plasmod_example.py
- tests/bluemira/base/test_parameter.py
- tests/bluemira/codes/test_interface.py
This makes it easier for users to modify the send/recv mappings of a code 
Additional `set_mappings` function. `ParameterMapping` now errors if you try to set other attributes to it
> Create mapping edit helper

- bluemira/equilibria/plotting.py
Protects against not being able to plot separatrix, enables merge of #569 
None
> 🎨 Dont crash on separatrix plotting failure

- .github/dependabot.yml
Adds neutronics-material-maker to upgrades ignores and makes the time slightly earlier so its finished for me starting
N/A
> 🎨 add ignore and change time for dependabot

- bluemira/builders/EUDEMO/pf_coils.py
- bluemira/builders/EUDEMO/plasma.py
- bluemira/builders/EUDEMO/tf_coils.py
- bluemira/builders/pf_coils.py
- bluemira/builders/plasma.py
- examples/design/EU-DEMO/EUDEMO_reactor.ipynb
- examples/design/EU-DEMO/EUDEMO_reactor.py
- examples/design/design_plasma.ipynb
- examples/design/design_plasma.py
- tests/bluemira/builders/EUDEMO/test_reactor.py
- tests/bluemira/builders/EUDEMO/test_tf_coils.py
- tests/bluemira/builders/test_plasma.py
N/A
This PR allows 3D builds to be created through a specified angle. This is intended to allow components to be visualised without wrapping around the whole reactor, allowing for cut-through views.
The `build_xyz` methods are given an optional `degree` parameter, which is 360 by default.
> Allow 3D builds through provided angle

- tests/bluemira/geometry/test_optimisation.py
We were getting this warning because of pytest class naming conventions (which makes sense):
```python
tests/bluemira/geometry/test_optimisation.py:29
/home/matti/code/bluemira/tests/bluemira/geometry/test_optimisation.py:29: PytestCollectionWarning: cannot collect test class 'TestOptimisationProblem' because it has a __init__ constructor (from: tests/bluemira/geometry/test_optimisation.py)
```
Renames this class so that it doesn't start with `Test`
N/A
> Fix a warning in geometry tests

- bluemira/equilibria/flux_surfaces.py
- tests/bluemira/equilibria/test_flux_surfaces.py
c.f. STEP teams chat
Adds a calculation for the outer upper and lower squareness of a closed flux surface, following Holcomb et al.'s definition of it, see: DOI:10.1063/1.3125934
`eq.analyse_core` now returns `CoreResults` in which the squareness is also included
> Add squareness calculation to `ClosedFluxSurface`

- bluemira/equilibria/find.py
- tests/bluemira/equilibria/test_find.py
Partially addresses #675 
Adds a `get_legs` function to `equilibria/find.py` to extract the separatrix legs from an equilibrium. Tested for SN and DN.
See above.
> Add get legs functionality to `equilibria`

- bluemira/geometry/bound_box.py
- bluemira/geometry/face.py
- bluemira/geometry/plane.py
- bluemira/geometry/shell.py
- bluemira/geometry/solid.py
- bluemira/geometry/wire.py
Reduces a bit of namespace noise in IDEs and should protect namespaces better in general
Adds __all__ to some files in geometry in which only a single class resides. Such that now one should not see `from bluemira.geometry.face import [BluemiraWire] as a suggestion.
N/A
> Geometry module  __all__ for some files

- conda/environment.yml
Conda updates are not covered by dependabot. This is a minor update to the fluids package.
None, the update makes their build reproducible
> ⬆️ Bump fluids to 1.0.17

- bluemira/magnetostatics/circuits.py
- bluemira/magnetostatics/trapezoidal_prism.py
Closes #723 
Fixes  `ArbitraryPlanarRectangularXSCircuit` to handle curvatures in both directions and some plotting inaccuracies that cropped up when the direction of curvature was not continuous.
Would greatly appreciate a benchmark with FEA, although once again for STEP's use case, it would be better just to use some `TrapezoidalPrismCurrentSource` and `CircularArcCurrentSource` for accuracy (minimal gain) and speed (substantial gain).
None
> Fix `ArbitraryPlanarRectangularXSCircuit` for re-entrant curvature

- BLUEPRINT/reactor.py
- BLUEPRINT/systems/plotting.py
- bluemira/builders/EUDEMO/reactor.py
- bluemira/codes/__init__.py
- bluemira/codes/interface.py
- bluemira/codes/plasmod/api.py
- bluemira/codes/plasmod/mapping.py
- bluemira/codes/process/__init__.py
- bluemira/codes/process/api.py
- bluemira/codes/process/run.py
- bluemira/codes/process/setup.py
- bluemira/codes/process/teardown.py
- bluemira/codes/utilities.py
- bluemira/codes/wrapper.py
- documentation/source/conf.py
- examples/design/EU-DEMO/EUDEMO_reactor.ipynb
- examples/design/EU-DEMO/EUDEMO_reactor.py
- tests/bluemira/codes/process/test_run.py
- tests/bluemira/codes/process/test_setup.py
- tests/bluemira/codes/process/test_teardown.py
This does a bit of cleanup of some of codes and does some renaming to enable generic wrappers that came up from discussions and thoughts on Friday. Code interfaces can now be loaded on the fly from anywhere with builtin location in `bluemira.codes` the preference.
`plot_PROCESS` has been renamed to `plot_radial_build` and `run_systems_code` to `systems_code_solver`. `systems_code_solver` now returns the solver object which needs to be run externally (allowing flexibility and reruns)
> Codes cleanup and finish generic wrapper

- bluemira/magnetostatics/baseclass.py
- bluemira/magnetostatics/biot_savart.py
- bluemira/magnetostatics/circuits.py
- examples/magnetostatics/helmholtz_example.ipynb
- examples/magnetostatics/helmholtz_example.py
- tests/bluemira/magnetostatics/test_circuits.py
Fixes a couple of problems in magnetostatics related to conventions:
* HelmholtzCage now patterned with the first circuit a theta=0
* CurrentSource rotation now right-handed and in degrees
Converts the magnetostatics example to a Jupyter notebook
See above
Degrees now the interface to magnetostatics rotations
> Fix HelmholtzCage and magnetostatics rotation conventions

- bluemira/codes/_freecadapi.py
- tests/bluemira/codes/test_freecadapi.py
- tests/bluemira/geometry/test_deprecated_tools.py
Closes #769 
Makes the return type of `bluemira.codes._freecadapi.center_or_mass` to a `np.ndarray`.
`BluemiraWire.center_of_mass` now returns a numpy array instead of a `FreeCAD.Base.Vector`. I think this was the original intent, and the behaviour of the two is not hugely different.
> Return numpy array on freecad center_of_mass

- .github/dependabot.yml
bandit can't be upgraded until flake8-bandit is
None
> 🐛 pin bandit in dependabot

- bluemira/equilibria/plotting.py
- scripts/install-process.sh
The error occurred during **build_EQ**  on the first iteration when running `step_reactor`  likely cause was the warning under failed to plot separatrix.  Changed the `EquilibriaError` to `Exception` to catch all errors in `def plot_separatrix`
> EquilibriaError to Exception

- documentation/source/mesh/mesh.rst
Docs weren't indented properly
None
> 📝 fix documentation indentation

- bluemira/equilibria/opt_problems.py
Quick bugfix for `CoilsetPositionCOP` and `NestedCoilsetPositionCOP.` 
Previously, at the end of an optimisation using these `OptimisationProblem`s, the objective function used to set the CoilSet to its optimal state was being called with the wrong set of arguments; this update fixes this by calling the `OptimisationProblem` objective directly.
> Bugfix for CoilsetPositionCOP and NestedCoilsetPositionCOP

- .flake8
- bluemira/base/builder.py
- bluemira/base/components.py
- bluemira/base/config.py
- bluemira/builders/EUDEMO/first_wall/__init__.py
- bluemira/builders/EUDEMO/first_wall/divertor.py
- bluemira/builders/EUDEMO/first_wall/first_wall.py
- bluemira/builders/EUDEMO/first_wall/wall.py
- bluemira/builders/EUDEMO/reactor.py
- bluemira/codes/_freecadapi.py
- bluemira/geometry/optimisation.py
- bluemira/geometry/parameterisations.py
- bluemira/geometry/tools.py
- bluemira/geometry/wire.py
- scripts/install-msh2xdmf.sh
- tests/bluemira/base/test_components.py
- tests/bluemira/builders/EUDEMO/first_wall/test_closed_first_wall.py
- tests/bluemira/builders/EUDEMO/first_wall/test_divertor.py
- tests/bluemira/builders/EUDEMO/first_wall/test_first_wall.py
- tests/bluemira/builders/EUDEMO/first_wall/test_wall.py
- tests/bluemira/codes/test_freecadapi.py
- tests/bluemira/geometry/test_optimisation.py
- tests/bluemira/geometry/test_tools.py
- tests/bluemira/geometry/test_wire.py
#642
Implements `FirstWallBuilder` class and adds the "First wall" component to the `EUDEMOReactor`.
Three builder classes have been implemented:
- `WallBuilder`: builds a closed wall shape, independent of divertor
- `DivertorBuilder`: builds the divertor components
- `FirstWallBuilder`: runs `WallBuilder`, cuts it off below the x-point, and uses `DivertorBuilder` to make a divertor in the gap.
Also added is the `MinimiseLength` geometry optimisation class, which minimises the length of a shape parameterisation with some constraints.
Some incomplete parts:
- Divertor targets are currently always vertical
- Divertor baffles are currently straight lines
- Only single-null plasmas with x-point at lower end are supported
Another note for reviewers, the function …
> Write initial first wall builder

- .github/dependabot.yml
- .pre-commit-config.yaml
- requirements-develop.txt
- setup.py
flake8-bandit has had a new release allowing us to upgrade bandit too
Additionally pinning versions implicitly is not possible in pre-commit at the moment: 
https://github.com/pre-commit/pre-commit    issue 582
None
> ⬆️ flake8-bandit upgrade

- bluemira/equilibria/find.py
- bluemira/equilibria/opt_objectives.py
- bluemira/utilities/opt_problems.py
- tests/bluemira/equilibria/test_coils.py
We are getting some warnings from deprecated behaviour in some of our dependencies
Fixes these warnings
Hopefully none
> Remove some warning messages from dependencies

- bluemira/utilities/error.py
Add full stops to the end of the docstrings in some error classes.
This is mostly to test code owners changes.
> Add full stops to error class docstrings

- bluemira/base/config.py
- bluemira/base/config_schema.py
- bluemira/codes/interface.py
- bluemira/codes/plasmod/api.py
- bluemira/codes/plasmod/mapping.py
- bluemira/codes/process/mapping.py
- bluemira/codes/process/run.py
- bluemira/codes/process/setup.py
- bluemira/codes/utilities.py
- data/reactors/EU-DEMO/systems_code/mockPROCESS.json
- tests/bluemira/codes/process/test_data/mockPROCESS.json
- tests/bluemira/codes/process/test_setup.py
Closes #867 
Fixes the problem with #848. This exposed that our PROCESS input file needs updating because string with commas dont get converted properly. 
```ipdb
ipdb> writer.data['iefrf'].get_value
*** ValueError: invalid literal for int() with base 10: '5,'
```
I took the second option of waiting for #833 to go in rather than updating our existing default input file. 
I've added a couple of tests to catch some of this.
This needs #833 to be merged 
None
> Re-add new process parameter mappings

- bluemira/base/builder.py
- bluemira/builders/EUDEMO/pf_coils.py
- tests/bluemira/builders/test_plasma.py
Closes #884 
This PR updates the configuration being used for the `ParameterFrame` in the base `Builder` class to be `Configuration` so that it has template values assigned from the start. We could make this more dynamic by passing in the Configuration/ParameterFrame class to use for the builders, but for this bug fix I think the current implementation in this PR should be enough.
None
> Use configuration for builder params

- bluemira/builders/EUDEMO/pf_coils.py
- bluemira/codes/_freecadapi.py
- bluemira/geometry/tools.py
- bluemira/geometry/wire.py
- bluemira/utilities/positioning.py
- tests/bluemira/builders/EUDEMO/test_pf_coils.py
- tests/bluemira/geometry/test_wire.py
- tests/bluemira/utilities/test_positioning.py
Closes #849 
Adds a `parameter_at(point, tolerance)` method to `BluemiraWire`
Adds a `split_wire(wire, vertex, tolerance)` function to `geometry/tools.py` (which is used above)
Moves the `PathInterpolator` and the rather crappy `make_coil_mapper` tools to pure primitive interpolation.
Note that a coil mapping test fails because I believe the `TaperedPictureFrame` is not correctly ordered (which should be fixed in #747)
See above, no changes to existing APIs.
Apologies for the rather noisy diff.. I've recently been shown the value of parametrising tests (apologies for taking so long to come round..)
> Primitive path interpolation

- bluemira/equilibria/flux_surfaces.py
- bluemira/radiation_transport/advective_transport.py
- examples/radiation_transport/heat_flux_calculation_DN.py
- tests/bluemira/radiation_transport/test_advective_transport.py
Closes #859
In some cases flux surfaces were effectively parallel and coincident with the first wall, likely triggering a linalgerror in `get_intersect` and thus not being registered as intersections. I think this part is fine. What is not fine is that the flux surfaces that lie effectively on top of the first wall were not being removed from the charged particle heat flux calculation.
None
> Catch no intersection between flux surface and first wall

- bluemira/equilibria/equilibrium.py
Closes #896
Adds a hotfix for loading FIESTA geqdsk files, in anticipation of future refactors addressing #318 properly.
As suspected, this is a simple case of different eqdsk conventions.
Note that the q profiles do not match up _exactly_, probably due to some previously mentioned discrepancies, and due to some "lacunes" of our q profile calculations on axis and at the separatrix.
N/A
> Hotfix: Equilibrium from a FIESTA eqdsk

- bluemira/equilibria/equilibrium.py
- bluemira/equilibria/physics.py
- bluemira/equilibria/profiles.py
- examples/equilibria/eudemo_2017.ipynb
- examples/equilibria/eudemo_2017.py
Addresses some of #675 
We had one too many functions claiming to calculate beta_p. There are two valid calculations for this now, one which is a Friedberg approximation, and the other which uses the full integrals.
Some function refactors to `calc_beta_p` and `calc_beta_p_approx`
> Refactor and clean-up `beta_p` calculations in `equilibria`

- bluemira/codes/process/setup.py
- tests/codes/process/test_run.py
A couple of the process tests were failing if process is installed. This fixes them
None
> 🐛 fix tests

- bluemira/equilibria/solve.py
As identified in discussions with G. Cunningham, the previous definition of the `CunninghamConvergence` criterion used in bluemira for slightly differs from that used in FIESTA. 
This PR makes the convergence parameter consistent (and dimensionless) for easier comparison with FIESTA runs, as intended.
> Update definition of Cunningham convergence to be consistent with FIESTA

- bluemira/builders/EUDEMO/maintenance.py
- bluemira/utilities/optimiser.py
- tests/builders/EUDEMO/test_maintenance.py
Starting to address #906 
Adds an optimisation problem for the sizing of the upper port and the segmentation of the breeding blankets in the poloidal plane.
None yet, still need to figure out how best to thread this into the reactor build chain. Thought I'd get the brains working first.
> EUDEMO upper port size optimisation problem

- bluemira/codes/_freecadapi.py
- tests/geometry/test_tools.py
Closes #965 
It makes `make_circle_arc_3P` consistent with `make_circle`
> Make make_circle_arc_3P consistent with make_circle

- .flake8
- bluemira/geometry/parameterisations.py
- bluemira/utilities/opt_variables.py
- tests/builders/EUDEMO/test_pf_coils.py
- tests/builders/EUDEMO/test_tools.py
- tests/geometry/test_face.py
- tests/geometry/test_offset.py
- tests/geometry/test_parameterisations.py
This creates a factory metaclass for picture frame and removes all extra pictureframe classes while keeping the same functionality. 
I have quite extensively used lambda functions assigned to variables which flake doesnt like but I couldnt think of a cleaner way to organise the code and loads of 1 lines functions seemed overkill. Better suggestions welcomed.
I still want to add a few more tests (for failure modes) but it is ready for a general structure review
@shaildesai96 you may be interested
For complex pictureframe structures you now specify the leg type when setting up the class eg full domed looks like
```python
PictureFrame(upper="CURVED", lower="CURVED")
```
> Refactor PictureFrame parameterisation

- requirements.txt
- setup.py
As said in #710 this was only a dependency for BLUEPRINT therefore removing
> ➖ Remove trimesh as a dependency

- bluemira/codes/interface.py
This can happen for old output files where mappings may not exist or be up to date.
> Modify `Teardown` to warn if values were not found in the output.

- documentation/source/geometry/geometry.rst
- tests/display/test_plotter.py
Closes #1017 
We used to import some modules into sub package namespaces. For some reason this still worked unless the file was run individually.
None
> 🐛 replace old geo import

- conda/environment.yml
Closes #997 
Closes #1020 
The FreeCAD conda package didnt pin pivy and the most recent pivy crashes our FreeCAD cad viewer.
None
> 🐛 FreeCAD pivy pinning, fixes CAD viewer

- setup.py
To avoid #1046 happening again set a lower limit on the mpl version in setup.py. I've tested mpl v3.5.0 onwards and everything seems to work
None
> 🚸 min mpl version

- documentation/developer/adr/0001-record-architecture-decisions.md
Adds a document that describes how we will format and record architectural decisions. The document also serves as an example of an ADR.
I've opted for putting the documents in the repository, the main advantages being that everyone can read and review them, and the point at which the decision was made is clear in the project's history. I've also gone with vanilla markdown, as I don't think these documents call for the extra maintenance required to build `rst`, there's also no reason they need to be linked to the user accessible documentation.
We should document decisions made in the upcoming workshop using these templates.
> Add proposal for ADR document templates

- README.md
No linked issues.
This pull request is to include in the publications' section of the README.md the most recent _Nuclear Fusion_ reference on MIRA modelling and systems analysis. 
I did not complete the following checks, as the modifications affect only the README.md file.
> Add Nucl. Fusion MIRA reference to README.md

- bluemira/builders/EUDEMO/_varied_offset.py
- bluemira/builders/EUDEMO/vacuum_vessel.py
- bluemira/builders/thermal_shield.py
- bluemira/codes/_freecadapi.py
- bluemira/geometry/face.py
- bluemira/geometry/tools.py
closes #1078 
Switches offset method in thermal shield to "intersect" which seems to be more robust in this case.
Adds some geometry closed checks.
N/A
> Increase robustness of EU-DEMO build and fix closure problem

- bluemira/base/components.py
- tests/base/test_components.py
Spurred by comments in #1145 
Generalise component search instead of homebrewed version. This really is a split out from #1145 because it was a bit out of scope to add a property search for a cad saver addition
New search for property function
> Generalise searching through a component

- .github/workflows/check_release_due.yml
The release checker was running on Sunday, not Monday. The 0th day is Sunday, not Monday! Whoops
> Fix check_release_due trigger schedule

- .github/workflows/ci.yml
The CI has been broken for a few days seemingly the fix is to use mambaforge instead of miniforge for the package resolving
None
> 💚 miniforge -> mambaforge

- requirements.txt
- setup.py
Upgrade scipy now numba-scipy allows a newer version
> Bump scipy from 1.6.2 to 1.7.3

- tests/display/test_plotter.py
- tests/equilibria/fem_fixed_boundary/test_fem_magnetostatic_2D.py
Removes warning from pytest 'UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.'
None
> 🚨 Remove mpl test warning about plotting without a gui backend

- .github/workflows/ci.yml
- requirements-develop.txt
- scripts/format_warning_report.py
- setup.py
Closes #1174 
Add steps to the CI to notify us if there are warnings in our PRs. These notifications take the form of PR comments that list the warnings that pytest has collected.
It also adds a step when the CI is run on "push", i.e. it's run on the develop/main branch, to generate a 'baseline' report. On PRs, we can then use the baseline report and only notify about _new_ warnings. Hopefully this makes managing new warnings more straight-forward.
This PR also adds the `--longrun` flag to the pytest call if `develop_dependencies` is the _head_ branch of PR. 
> Add warnings to CI and run more tests for the develop dependencies PRs

- .github/workflows/ci.yml
- examples/convert_py_to_ipynb.py
Enables notebook checking in CI and slightly clean the converter script
You now need to notebook your examples
> 🧱 Enable forced example notebooks along with some converter script fixes

- bluemira/display/auto_config.py
- tests/display/test_auto_config.py
Closes #264
By using multiprocess with 1 core we can timeout the display checking function and produce a warning on timeout
None
> ⚡️ Timeout display check

- .github/workflows/ci.yml
- .github/workflows/comments.yml
Closes #1268 
This splits out the warnings comment to be fixed in a later PR so it doesn't fail our CI
None
> 👷 split out warnings comment from main CI workflow

- bluemira/base/parameter_frame/_parameter.py
- bluemira/builders/__init__.py
- bluemira/builders/pf_coil.py
- tests/builders/test_pf_coil.py
Restores the PF coil builder to the `builders` module, using new parameter and builder architecture.
This probably needs more tests, but I couldn't really think of any that didn't involve delving into the component tree structure. Probably a sign that we need some accessors on `PFCoil`, but I guess we just add those as and when we have a need for them - along with tests.
> Add pf coil builder

- bluemira/builders/shapes.py
- bluemira/geometry/optimisation.py
- bluemira/utilities/opt_problems.py
- examples/design/design_shapes.ipynb
- examples/design/design_shapes.py
Closes #1322 
Fixes the broken example (`examples/design/design_shapes.py`), which was using the old API for setting up an optimisation problem.
We need to look into writing some documentation for setting up optimisation problems. I think we could also consider writing a `run_geometry_optimisation` function that wraps all this object creation; I believe this would significantly lower the barrier to entry,
> Error running design_shapes example

- bluemira/base/builder.py
- bluemira/builders/pf_coil.py
- bluemira/builders/plasma.py
- bluemira/builders/tools.py
- tests/base/test_builder.py
- tests/builders/test_tools.py
Adds some helper functions for builders. Unsure about whether I should get the `component` in the `component_tree` function, it feels nicer from usability as written though.
Possibly overkill on the `get_n_sectors` tests but couldn't think of a nicer test/ less of them (~100 now). Could halve it again?
None
> ✨ Component tree method and get_n_sectors function

- bluemira/codes/_freecadapi.py
- bluemira/geometry/face.py
- bluemira/geometry/wire.py
- tests/codes/test_freecadapi.py
Part of #1347 and #1319 
This makes offset wire a bit more robust and therefore hopefully most of the build
> 🐛 topology workaround

- bluemira/equilibria/opt_constraints.py
- bluemira/geometry/_deprecated_tools.py
Part of #1323 
Removes `Loop` from opt_constraints. It feels like `_deprecated_tools` will be the last to go so I've moved the interpolation functionality there for now
None
> 🎨 Remove Loop from opt_constraints

- bluemira/base/builder.py
- bluemira/base/designer.py
- bluemira/builders/cryostat.py
- bluemira/builders/pf_coil.py
- bluemira/builders/plasma.py
- bluemira/builders/thermal_shield.py
- tests/base/test_designer.py
- tests/builders/test_cryostat.py
- tests/builders/test_pf_coil.py
- tests/builders/test_plasma.py
- tests/builders/test_thermal_shield.py
Updates the `Designer` interface to include a mandatory `run` method, and optional `read` and `mock` modes.
Makes `Builder` and the base `Builders` agnostic of `Designer`s - this means we can remove all the in-out designers we were having to define.
I haven't looked at updating the EUDEMO designers yet - maybe we should do those separately.
> Refactor Designer

- bluemira/base/parameter_frame/_frame.py
- bluemira/base/parameter_frame/_parameter.py
Fixes a couple of typing issues that meant I was not getting autocomplete in cases where I was using the `classmethod` constructors of `ParameterFrame`.
Also rearranges the method declaration order in `ParameterFrame` so that all the constructors are together.
> Improve ParameterFrame typing

- tests/base/parameterframe/test_parameterframe.py
Adds test that parameter value changes in a 'sub-frame' are propagated to the 'parent' frame.
Small refactor of some repeated test setup.
> Add test for paramteterframe update propagation

- bluemira/base/parameter_frame/_frame.py
- examples/design/EU-DEMO/EUDEMO_tests/equilibria/test_data/params.json
- examples/design/EU-DEMO/EUDEMO_tests/ivc/test_divertor_silhouette.py
- examples/design/EU-DEMO/EUDEMO_tests/ivc/test_ivc_boundary.py
- examples/design/EU-DEMO/EUDEMO_tests/ivc/test_plasma_face.py
- examples/design/EU-DEMO/EUDEMO_tests/ivc/test_wall_silhouette.py
- examples/design/EU-DEMO/EUDEMO_tests/test_blanket.py
- examples/design/EU-DEMO/EUDEMO_tests/test_vacuum_vessel.py
- tests/base/parameterframe/test_parameterframe.py
- tests/base/test_builder.py
- tests/builders/test_cryostat.py
- tests/builders/test_divertor.py
- tests/builders/test_pf_coil.py
- tests/builders/test_thermal_shield.py
Removes the requirement to have the `name` key when defining parameters in a dict or JSON file using the new ParameterFrame class.
> Remove repeated name in param definitions

- bluemira/radiation_transport/advective_transport.py
- examples/radiation_transport/heat_flux_calculation.ipynb
- examples/radiation_transport/heat_flux_calculation.py
- examples/radiation_transport/heat_flux_calculation_DN.ipynb
- examples/radiation_transport/heat_flux_calculation_DN.py
- tests/codes/plasmod/test_solver.py
- tests/radiation_transport/test_advective_transport.py
Part of #1422 
Remove use of `ParameterFrame` in the `radiation_transport` module. It's replaced with a dataclass.
Initialise a `ChargedParticleSolver` with a dictionary, instead of a `ParameterFrame`.
> Remove ParameterFrame from radiation_transport module

- .github/workflows/ci.yml
Codecov upload is failing more. This makes it so the CI will only fail when the CI is run on main and develop for the codecov upload
> 👷 only fail CI if coverage upload fails on develop or main

- README.md
We should probably link to the release docs rather than dev docs from the badge. Unfortunately I've never found a way to do it dynamically 
> 📝 change badge to release docs

- pyproject.toml
Until #1452 and until #1457 can be merged we should limit matplotlib, because it breaks things otherwise
None
> 📌 freeze mpl version more strictly

- .github/dependabot.yml
We don't currently update GH actions and it seems there was a deprecation so we now have lots of warnings on the CI.
This adds github actions to dependabot (PRs on to develop)
None
> 👷 Autoupdate github actions

- .github/workflows/check_release_due.yml
- .github/workflows/comments.yml
- .github/workflows/release.yml
`::set-output name=` in github actions has been deprecated replaced with `>> $GITHUB_OUTPUT` as described:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> 👷 ::set-output is deprecated 

- .github/workflows/ci.yml
- bluemira/codes/plasmod/api/_teardown.py
- bluemira/equilibria/coils.py
- bluemira/equilibria/equilibrium.py
- bluemira/geometry/parameterisations.py
- documentation/source/conf.py
This makes most methods documented. Something I've found, if `__all__` is defined and the object is not in all it doesn't get documented. Should have a look through as part of #1418 to make sure we're not missing anything.
Made the documentation build multicore if they exist (`-j auto`)
Hacks the autoapi inheritance diagrams to have the correct uri
None
> 📝 Documentation infrastructure improvements

- bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
- bluemira/equilibria/fem_fixed_boundary/utilities.py
Requires #1067 
Supercedes #1404 
Closes #1255 
Calculates the psi axis via optimisation rather than taking the maximum of the grid points in the fixed boundary equilibrium solver.
For the example `examples/equilibria/fem_fixed_boundary/equilibrium_example.py` on `ivanmaione/clean_fixed_boundary` exhibits slightly improved convergence behaviour:
There are two additional internal G-S iterations (outer iterations 1 and 4), but 7 fewer in total, as the last outer iteration is not required (in this example).
As for the 95th flux surface extremum finding, just using scipy `minimize` for now. Best to pick up #1253 on both counts in a separate future PR (not so urgent).
N/A
> Improve psi axis finding in fixed boundary equilibrium

- bluemira/base/components.py
- tests/base/test_components.py
Closes #955
Possible fix, other options considered were using `__eq__` but I would only check `self.name==other.name` which made lead to some odd situations. 
You cant have the same named components at the same level
> 🐛 solve components named the same at the same level

- documentation/source/codes/codes.rst
Updates the Codes docs slightly, adds MappedParameterFrame and move ParameterMapping docs here too
based of #1567 
None
> 📝 Codes and MappedParameterFrame docs

- documentation/source/base/parameter.rst
Removes incorrect imports from a couple of `parameter.rst`'s code examples.
> Remove imports from parameter.rst code examples

- bluemira/geometry/parameterisations.py
- tests/geometry/test_parameterisations.py
`inner` PictureFrame parameterisation adjustment doesnt work if directly specified with enum. This fixes it and adds some tests to that effect.
Also removed limitation so you can now have tapered inner with either domed or flat sections
None
> 🐛 fix enum specified inner and remove limitations

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/eu_demo_bug_report.md
- .github/ISSUE_TEMPLATE/eu_demo_feature_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/step_bug_report.md
- .github/ISSUE_TEMPLATE/step_feature_request.md
- .github/pull_request_template.md
Closes #1626 
Comment out the instructions, so the writer can still see them, but the instructions are not rendered in the markup. This saves us having to delete a lot of the template in order to have a clean ticket.
Nope
> Comment issue/PR template instructions

- .pre-commit-config.yaml
Flake8 has shutdown its gitlab repo and moved to github 
None 
> 👷 flake8 has moved repo location

- examples/geometry/plotting_tutorial.ipynb
- examples/geometry/plotting_tutorial.py
I was asked to add a little for geometry plotting example only showing the wires not the faces
None
> ✨ Add show_faces to geometry plotting tutorial

- tests/utilities/test_optimiser.py
Closes #1652 
Fixes the optimiser test.
I went through the whole damn thing, checked the gradient calculations of the toy problem, and went pretty deep into what we have. I've narrowed it down to two things:
* Invalid starting solution does not guarantee convergence (fixed)
* Likely something wrong with the SLSQP implementation in NLOpt (unconfirmed)
* Partly related to the strange problem formulation I had chosen in which 3 of the variables were basically dummy equality constraints that didn't feed into the objective function, but it seems that very occasionally SLSQP's Hessian calculation (again probably) causes a starting solution of zeros to be passed into the objective function repeatedly until the number of iterations is reached.
* This is probably a very strange edge case in the …
> Fix occasional optimiser test failure

- bluemira/equilibria/find.py
- pyproject.toml
- requirements.txt
Closes #1452 
Replaces use of matplotlib private functionality for contour generation on quad grids (now removed in more recent matplotlib versions) with contourpy.
Note that `TriContourGenerator` in matplotlib is still presently used.
N/A
> Replace matplotlib private `QuadContourGenerator` with contourpy

- eudemo/README.md
- eudemo/config/build_config.json
Get rid of the absolute paths in the EUDEMO reactor build's config.
You must now run the `reactor.py` file from within the `eudemo` directory.
> Remove absolute paths from eudemo config

- documentation/source/installation.rst
> Add curl to install instructions [required for fresh Ubuntu 22.04]

- bluemira/codes/plasmod/api/_inputs.py
- bluemira/codes/plasmod/mapping.py
Adds a model selector for two distinct options in PLASMOD.
Closes #{ID}
Changes the default model to fully_relaxed, meaning that p' and FF' correspond more correctly to the output plasma current profile.
> Add SafetyProfileModel to PLASMOD api

- bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
Noticed that plasma current correction factor k was high. Realised we were missing a term when combining the flux functions.
For flux functions that correspond correctly to the total plasma current, k is now generally very close to 1 (as expected)
> Add missing 2pi factor in FEM fixed boundary equilibrium solver

- documentation/source/conf.py
Closes #1604 
Hard codes the html title stripping the version git hash. Other option is to just remove 'dirty' from the end of the string.
The git hash revision is still displayed at the bottom of each page.
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_title
None
> 🐛 set html title without git hash

- bluemira/codes/_freecadapi.py
- bluemira/geometry/tools.py
- tests/codes/test_freecadapi.py
Closes #1309
I created it as a decorator so that the api would be constant but I'm open to other options. 
Possibly could generalise it further and have the error to catch and the error to raise as input and put the function in utilities
`tools.convert` will now raise a geometry error instead of a FreeCADError on failure
> 🥅 catch freecad error

- bluemira/geometry/coordinates.py
- tests/geometry/test_inscribed_rect.py
When trying to catch errors the indexing wasnt nested deep enough.
This is very hard to see if it fixes the occasional failure we see because I haven't had a local failing example
> 🐛 fix indexing bug in inscribed_rect test

- bluemira/display/auto_config.py
See below comments
~~Our current seaborn config is a bit broken below are the differences (some highlights eg `colour: .15`) (- ours, + default).~~
```
-  'axes.axisbelow': True,
+  'axes.axisbelow': 'line',
-  'axes.edgecolor': '.15',
+  'axes.edgecolor': 'black',
-  'axes.labelcolor': '.15',
+  'axes.labelcolor': 'black',
-  'axes.labelsize': 10.792727272727275,
+  'axes.labelsize': 'medium',
-  'axes.titlesize': 8.993939393939394,
+  'axes.titlesize': 'large',
-  'grid.color': '.8',
+  'grid.color': '#b0b0b0',
-  'legend.fontsize': 9.893333333333334,
+  'legend.fontsize': 'medium',
-  'legend.title_fontsize': 10.792727272727275,
+  'legend.title_fontsize': None,
-  'lines.solid_capstyle': <CapStyle.round: 'round'>,
+  'lines.solid_capstyle': <CapStyle.projecting: 'projecting'>,
- …
```
> Cleanup seaborn config

- bluemira/equilibria/coils/_coil.py
- bluemira/equilibria/constants.py
If the discretisation of a coil was  >=1m it wouldn't be discretised this probably hasnt come up yet because a PF coil with a 1m width/height is very big. The default is now `np.nan` which is checked for when discretising.
Also moved minimum discretisation to constants
dicretisation defaults to `np.nan` instead of 1 but this has the same effect because of the changed discretise check
> 🐛 remove weird discretisation condition for >1m coils

- bluemira/equilibria/shapes.py
- tests/equilibria/test_shapes.py
Adds an alternative flux surface parameterisation which could be pretty useful for EU-DEMO, as it feels like it does a better job at capturing the upper surface. There are a couple of problems with the parameterisation as described, but the fudges I found produce what feels like a good shape.
Adds `flux_surface_kuiroukidis` to `equilibria.shapes.py`
> Add Kuiroukidis flux surface parameterisation

- documentation/source/conf.py
- pyproject.toml
This adds a basic mypy config with the eventual long term aim of enabling mypy in the CI system in some form.
It also modifies the API documentation so that types no longer need to be specified in the docstring. 
Types should now be specified in the function signature, they will be automatically added to both the signature and docstring when the documentation is built. Up for discussion however, we may just want the types in the description or signature.
None
> ✨ Mypy config and typing in documentation modification

- .pre-commit-config.yaml
- requirements-develop.txt
The `isort` installation procedure has somehow broken without changing the version see https://github.com/PyCQA/isort/issues/ 2083
Upgrading isort fixes the problem (or more accurately bypasses it)
> ⬆️ upgrade isort

- documentation/source/structural/structural.rst
Also the link contains an old AWS AccessID that has expired which gets flagged as a security issue
> 📝 remove dead link in structural docs

- scripts/install-process.sh
PROCESS install has needed to be updated before a release because the FORD repository has moved which breaks the PROCESS install. This hotfix tag slightly ahead of 2.3.0. Once PROCESS has a new release and #1685 is done this is irrelevant.
> ⬆️ use the PROCESS hotfix tag

- bluemira/codes/plasmod/api/_plotting.py
- bluemira/codes/plasmod/api/_solver.py
Closes #{ID}
Applies a hack to PLASMOD output flux functions
In the case of a sawtoothed q profile:
In the case of a fully relaxed q profile:
@ivanmaione I note that the equilibrium does not quite converge after 15 iterations...
> Add PLASMOD post-processing flux function hack

- .github/workflows/examples.yml
- scripts/run_examples.py
The `ext_code_script` is not an example so shouldnt run but should be executed by the example
None
> 🐛 exclude external code script from examples ci run

- bluemira/equilibria/shapes.py
- tests/equilibria/test_flux_surfaces.py
- tests/equilibria/test_shapes.py
Notice that `ManickamLCFS` and `CunninghamLCFS` do not match the input delta. AFAICT this is not my fault.
> Add `ZakharovLCFS` and tests

- documentation/source/conf.py
- examples/design/simple_reactor.ex.py
Links to other notebooks didn't work before unless you used the '.ipynb' extension for the rendered docs.
Obviously that file doesnt exist so you had a choice of working in docs or working in the notebook.
This is a naiive hack on those links to piggyback on the change to html so the links will now work in both places 
> 📝 Fix '.ex.py' links in docs

- requirements-examples.txt
Cherry picks  #1932 onto develop because of the security notice
> Bump ipython from 8.9.0 to 8.10.0

- bluemira/base/components.py
- bluemira/base/reactor.py
- examples/design/simple_reactor.ex.py
- tests/base/test_components.py
Changed Reactor show_cad to use filter_components and changed the interface to accept *dims and kwarg dim. Also added tests.
Closes #1076
Implemented a method on Component that copies and filters the tree based on the given names.
The filtering gets each component given in `names` and removes the sibling nodes of that component whose name isn't in `names`
* `show_cad` in Reactor has changed to accepts string args (*dims). If kwarg "dim" is given, only it is used.
* added `copy `to Component
* added `filter_components` to Component
> Added copy and filter_components to Component. 

- bluemira/equilibria/flux_surfaces.py
- tests/equilibria/test_flux_surfaces.py
Closes #1981 
As we stripped out functionality from `Coordinates` this stuff got lost. I've put in a fix that does not change the API of `Coordinates`, checks for planar `Coordinates` when used in a `FieldLineTracer` and adds some proper tests that check for collision of the field line end point with the provided boundary.
> Fix connection length calculation when using `Coordinates`

- bluemira/builders/plasma.py
- eudemo/eudemo/ivc/divertor_silhouette.py
- eudemo/eudemo/vacuum_vessel.py
This is a work around for the bug @hsaunders1904  pointed out in #1965 and a workaround for the divertor dome.
If the outer divertor target was lower than the inner target the dome would be put on the wrong flux line.
There is still a bug in the blanket segmentation, for some reason the boolean cut produces a valid face and an invalid face (L204 eudemo/blanket.py).
> Avoid some CAD bugs in EUDEMO

- bluemira/base/constants.py
- bluemira/base/parameter_frame/_frame.py
- bluemira/base/parameter_frame/_parameter.py
- tests/base/parameterframe/test_parameter.py
- tests/base/parameterframe/test_parameterframe.py
When we are updating from an external code sometimes the value doesnt exist in the output we warn and set it to None . This will then fail when we update subsequent frames.
The fix allows the `None` to be passed through harmlessly 
> 🐛 allow setting None when updating a parameterframe

- bluemira/codes/process/mapping.py
Closes #{ID}
Gets rid of a couple of warnings, but I am concerned that PROCESS no longer seems to be outputting `thkcas`. We've been implicitly using this for a while but it's been being set to 0.0. Now that it is a None, we get an error in the TF coil build, and I can no longer be certain that we are correctly interpreting the radial build from PROCESS (at least as far as the TF coil is concerned).
@je-cook
@ajpearcey
> Update a couple of obsolete vars in PROCESS mapping

- bluemira/equilibria/constants.py
- bluemira/equilibria/equilibrium.py
- bluemira/equilibria/physics.py
- bluemira/equilibria/profiles.py
- bluemira/equilibria/solve.py
- examples/equilibria/eudemo_2017.ex.py
- tests/equilibria/setup_methods.py
- tests/equilibria/test_equilibrium.py
Closes #1042
Adds a `BetaLiIpProfile` to free boundary equilibrium solver, which is just resurrected stuff from BLUEPRINT. Turns out it works pretty great for EU-DEMO, at least for the example considered. It's not the most beautiful implementation, and uses scipy optimize at present, which I hate with a passion, but... it works out of the box.
> Add `BetaLiIpProfile` to free boundary equilibrium solver

- bluemira/codes/process/_inputs.py
> More obsolete PROCESS variables in inputs

- bluemira/equilibria/fem_fixed_boundary/utilities.py
Closes #{ID}
For bad/difficult profiles, I've occasionally witnessed a RuntimeError, when calculating the plasma shape params. This fails hard, and the mesh point is a fair enough estimate of the extrema anyway, so we can just fall back to it softly with a warning.
> Catch `RuntimeError` which occasionally crops up in fixed boundary equilibrium solver.

- bluemira/geometry/face.py
- bluemira/geometry/shell.py
- bluemira/geometry/solid.py
- bluemira/geometry/wire.py
Closes #{ID}
Bug when getting the list of thing that is a thing..
```python
>>> from bluemira.geometry.tools import make_circle
>>> c = make_circle()
>>> c.wires
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/matti/code/bluemira/bluemira/geometry/wire.py", line 250, in wires
return tuple(self)
TypeError: 'BluemiraWire' object is not iterable
```
> Remove bad tuples in `BluemiraGeo` subclasses.

- bluemira/codes/_freecadapi.py
- bluemira/codes/_polyscope.py
- bluemira/display/displayer.py
- tests/display/test_displayer.py
I broke the show_cad API when #1033 was merged this should unbreak it
@CoronelBuendia 
> Unbreak `show_cad` api

- bluemira/base/reactor_config.py
- eudemo/config/build_config.json
- eudemo/eudemo/coil_structure.py
- eudemo/eudemo/reactor.py
- tests/base/reactor_config/data/reactor_params.global.json
- tests/base/reactor_config/test_reactor_config.py
Closes #1991 
Moves EUDEMO reactor.py to using the new ReactorConfig object.
The ReactorConfig class was changed a bit to make it more ergonomic to use. It no longer throws if you try to access keys that don't exist and only warns if return objects are empty.
This fits in with the way things were done in EUDEMO and makes sense because those parameters/configs might be added in the future.
A path to a json file holding global_params can now optionally be given. This lets one separate global params from the build config which is how EUDEMO has been laid out.
In the future, we could isolate params per component. See Issue #2086.
Options to silence the warnings were also added.
ReactorConfig
> Move EUDEMO params and config to the new ReactorConfig object

- bluemira/base/builder.py
- tests/base/test_builder.py
> Make `Builder` and `Designer` consistent when handling `build_config` in `__init__`

- bluemira/builders/tf_coils.py
- bluemira/magnetostatics/circuits.py
- tests/builders/test_tf_coils.py
Requires #2065 
Closes #1735 
OK, I've had a quick bash at this, but before I go much further, I'd like to just summarise what I'm going for, and check it will do what you want, @bielsnohr.
I've added an argument to the `RippleConstrainedLengthGOP` `__init__` in which a `RipplePointSelector` can be provided. This is not the nicest API, and I'm sure there are nicer ways to instantiate these things which I will improve on later.
I kind of need a class or protocol to capture the following options:
* Equi-spaced points at which the ripple shall be calculated
* Equi-spaced points above a certain minimum radius (could be combined with the above)
* Direct specification of the points at which ripple should be calculated (your use case?)
* Finding the point of maximum ripple along a wire
Please …
> Add selection strategies for the points at which TF ripple is constrained

- bluemira/base/look_and_feel.py
- bluemira/fuel_cycle/analysis.py
As mentioned in https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/2058#discussion_r1146178193
We dont need this anymore as it can be replaced by rich's `progress.track`. This is the only use of it in the whole codebase
BluemiraClock is gone
> 🔥 remove BluemiraClock

- bluemira/equilibria/coils/_grouping.py
- tests/equilibria/test_coils.py
Closes #{ID}
When repadding a `Circuit` the padding was being added to all axes of the array whereas we only want to pad the end of the last axis
~TODO a test~ Done
> 🐛 Fix quad padding for coil circuits

- bluemira/optimisation/_geometry/optimise.py
- bluemira/optimisation/_geometry/parameterisations/tools.py
- bluemira/optimisation/_nlopt/optimiser.py
- bluemira/optimisation/_optimise.py
- bluemira/optimisation/_optimiser.py
- bluemira/optimisation/_tools.py
Closes #2190 
Part of #2189 
Removes typing from the docstrings of functions/classes in the `optimisation` module.
Nope
> Remove typing from optimisation module's docstrings

- bluemira/optimisation/_geometry/_tools.py
- bluemira/optimisation/_geometry/optimise.py
- bluemira/optimisation/_optimise.py
- tests/optimisation/test_geometry.py
Closes #2203 
Add `koz_discretisation` and `kiz_discretisation` arguments to `optimise_geometry`. This allows users to set the discretisation of the given keep-in/out zones in geometry optimisations.
> Allow customisation of keep in/out zone discretisation

- bluemira/equilibria/profiles.py
- bluemira/magnetostatics/trapezoidal_prism.py
Some warnings have been introduced as part of the numba 0.57 update. This should be reviewed thoroughly. I don't think any behaviour will change (and the tests still pass locally)
this is being merged into develop_dependencies so we have a few weeks
https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit
> 🚨 Fix warnings in numba 0.57

- documentation/source/conf.py
Closes #2227 
There area few extension we can enable for our notebook renderer see a full list here: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-extensions
Seem to work:
None
> 🐛 enable dollarmaths in notebook example docs

- bluemira/base/components.py
- bluemira/base/reactor.py
- tests/base/test_reactor.py
Closes #2207 
Closes #2163 
This PR adds some filtering opportunities to the `ComponentManager` and `Reactor` it doesn't use the  `Component._get_thing` filtering mechanism that I add last year (and forgot about) so that the tree is kept intact in the filtering. 
At the moment you can only filter on `PhysicalComponent` properties which I will try and find a way around but as `Component` doesnt hold and information and is just a node linker that may be acceptable. We can already filter by node with the combination of `with_component` and `dims`.
UPDATE: restriction removed
> Material filtering on Managers

- bluemira/optimisation/_geometry/_tools.py
- bluemira/optimisation/_geometry/_typing.py
- bluemira/optimisation/_typing.py
- tests/optimisation/test_geometry.py
Closes #{ID}
At present, you get an error if you specify a constraint dict with  `"df_constraint": None` in `optimise_geometry` which is not the case in `optimise`.
> Allow `"df_constraint": None` in optimise geometry

- documentation/source/base/components.rst
- documentation/source/base/design_build.dot
Adds documentation of the Reactor object to the base module docs and links to it from the introduction.
> 📝 Add reactor docs to introduction

- bluemira/optimisation/_nlopt/conditions.py
- tests/optimisation/test_nlopt.py
When setting the stopping conditions eg `{"max_eval": 1e6}` this will try and convert floats to ints (with a warning). It feels a bit more user friendly to me.
> 🚸 Force type of max eval

- bluemira/codes/_freecadapi.py
When testing #2167 it would error with the polyscope backed because we were trying to stack empty arrays. 
This fixes that
my test line:
```python
from bluemira.base.reactor import FilterMaterial, Void
reactor.show_cad("xyz", n_sectors=3, filter_=FilterMaterial(keep_material=Void, reject_material=None), backend='polyscope')
```
> 🐛 Fix collect verts and faces for polyscope viewing

- bluemira/geometry/tools.py
- bluemira/optimisation/_geometry/optimise.py
- bluemira/optimisation/_optimise.py
- bluemira/optimisation/_optimiser.py
- tests/optimisation/test_optimise.py
Partly addresses #2256.
Adds code to `optimise` that checks whether inequality constraints have been satisfied within tolerance, and prints a warning if not.
I've changed the warning message ever so slightly, it now shows the constraint type and number, and the index into that constraint vector when warning of a violated constraint - instead of concatenating all the constraints into one long vector. I think this makes it a bit clearer which constraints are being violated - we could even consider adding the ability to label a constraint in the future.
> Check constraints in optimisations

- bluemira/optimisation/_geometry/_tools.py
- bluemira/optimisation/_geometry/optimise.py
- bluemira/optimisation/_geometry/problem.py
- tests/optimisation/geometry/test_geometry.py
Closes #2274 
Removes keep-in zones from `optimise_geometry` and `GeomOptimisationProblem`.
> Remove keep in zones

- bluemira/codes/_freecadapi.py
- examples/geometry/geometry_tutorial.ex.py
- tests/_helpers.py
- tests/codes/test_freecadapi.py
Fixes some FreeCAD saving methods, checks in the test for skip on dependency availability and removes some tests that will never pass.
Adds the new saving to the examples.
~TODO check for other occurances of old saving examples~ cant find any
None
> 🎨 Improve freecad saving, examples and tests

- bluemira/codes/_freecadapi.py
- bluemira/codes/_polyscope.py
- bluemira/display/displayer.py
The merge of #1918 missed a bit of show cad mechanics. It was not caught by our CI because  we patch out viewing of CAD because its headless. Caught by @oliverfunk in https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/2276#discussion_r1205802348.
Bonus it removes the type checking geometry `BluemiraGeo` import from the FreeCAD api.
It does slightly change the `_freecadapi` interface but nothing user level.
> 🐛 Fix show cad and rearrange typing

- bluemira/base/components.py
- bluemira/base/reactor.py
- bluemira/codes/_freecadapi.py
- bluemira/equilibria/fem_fixed_boundary/file.py
- bluemira/geometry/tools.py
- bluemira/utilities/plot_tools.py
- examples/codes/equilibrium_plasmod_example.ex.py
Closes #2314
Deprecates the use of filter_ and formatt parameters throughout the codebase.
filter_ is changed to component_filter
formatt is changed to cad_format or file_formatt (for images mostly)
A number of interfaces have changed but deprecation notices have been used so the same interface can be used.
> Depricate filter_ and formatt

- bluemira/geometry/parameterisations.py
- examples/geometry/optimisation_tutorial.ex.py
Closes #{ID}
Docstring indentation got mangled by me somehow. Needs fixing, as all the other `feature/new_optimisation_module` PRs are failing!
This commit exists in #2331, but let's get this in on its own.
> Fix docstring indentation

- bluemira/optimisation/__init__.py
- bluemira/optimisation/_geometry/_tools.py
- bluemira/optimisation/_geometry/optimise.py
- bluemira/optimisation/_geometry/problem.py
- tests/optimisation/geometry/test_geometry.py
Refs #2189 
Addresses issues flagged in https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/2238#issuecomment-1564046300
Expose more keep-out zone features through the `optimise_geometry` and `GeomOptimisationProblem` API.
This is done using a new class `KeepOutZone` which is constructed using a `BluemiraWire` and, optionally, discretization configuration and constraint tolerance.
> Make keep-out zones more customisable

- bluemira/optimisation/_nlopt/functions.py
- bluemira/optimisation/_nlopt/optimiser.py
- bluemira/optimisation/_optimiser.py
- tests/optimisation/test_nlopt.py
Closes #2335 
On a round-off error, we were actually returning the _initial_ parameterisation, not the parameterisation from the previous iteration 😱.
I'm a little dubious of the way this was being handled in the old optimiser. I found it necessary to copy the NLOpt array to get the documented behaviour (at least what I thought the documented behaviour meant). This was not being done in the old optimiser classes.
I thought we were intending to return the parameterisation from the iteration _before_ we got the round-off error (this is what I've implemented). But it occurs to me now that maybe we wanted the iteration that actually caused the round-off error (I believe this is the behaviour the old optimiser has. Couldn't this mean we get a bunch of `NaN`s?, though).
@CoronelBuendia any …
> Fix returning initial value and not previous iteration on round-off error

- bluemira/optimisation/_geometry/optimise.py
- bluemira/optimisation/_nlopt/optimiser.py
- bluemira/optimisation/_optimise.py
- bluemira/optimisation/_optimiser.py
- documentation/source/optimisation/optimisation.rst
Closes #2252 
Fix up the docstrings in the optimisation module, as well as a small update to the optimisation RST docs to make vectors bold in the maths.
> Fix inline latex not rendering in optimise docstring

- .github/workflows/ci.yml
FETCH_HEAD refers to the first branch in a git fetch not the last
tested on this CI run https://github.com/Fusion-Power-Plant-Framework/bluemira/actions/runs/5401454617/jobs/9811280435 see the passed on the copyright check
> 🐛 Fix FETCH_HEAD bug

- bluemira/base/constants.py
- bluemira/base/parameter_frame/_frame.py
Hard limits the table size of a printed parameterframe
> ✨ Max column size for tabulated ParameterFrame

- bluemira/equilibria/opt_problems.py
- bluemira/equilibria/optimisation/constraint_funcs.py
- bluemira/equilibria/optimisation/constraints.py
- bluemira/equilibria/optimisation/objectives.py
- bluemira/equilibria/optimisation/problem/__init__.py
- bluemira/equilibria/optimisation/problem/_breakdown.py
- bluemira/equilibria/optimisation/problem/_minimal_current.py
- bluemira/equilibria/optimisation/problem/_nested_position.py
- bluemira/equilibria/optimisation/problem/_position.py
- bluemira/equilibria/optimisation/problem/_tikhonov.py
- bluemira/equilibria/optimisation/problem/base.py
- bluemira/equilibria/optimisation/problems.py
- bluemira/equilibria/solve.py
- examples/equilibria/eudemo_2017.ex.py
- examples/equilibria/single_null.ex.py
- tests/equilibria/test_optimiser.py
Partially addresses #2383 
This needs a lot of cleaning up. I've been rushing through it a bit, trying to get things in (at least) working order. I'm expecting flake8 to tell me off.
The idea has basically been to copy across all the old classes in `equlilibria.opt_[problems|constraints|constraint_funcs|objectives]` into a new module: `equilibria.optimisation`. `CoilsetOptimisation` no longer inherits from `OptimisationProblem`, it's now just an abstract class where you need to define `optimise` which returns a `CoilsetOptimiserResult`. The approach I've taken is to make a call to `bluemira.optimisation.optimise` in the `CoilsetOptimisation.optimise` implementations.
The old coilset optimisation objectives have been re-written to match a new `ObjectiveFunction` interface. Which requires …
> Retrofit coilset optimisations to use new optimiser interface

- bluemira/builders/coil_supports.py
- bluemira/equilibria/opt_constraint_funcs.py
- bluemira/equilibria/opt_constraints.py
- bluemira/equilibria/opt_objectives.py
- bluemira/equilibria/opt_problems.py
- bluemira/geometry/optimisation/_optimisation_old.py
- bluemira/utilities/opt_problems.py
- bluemira/utilities/optimiser.py
Closes #2337 
Adds deprecation warnings to the old optimisation modules and to some other bits of code whose usage will change due to the new optimisation module.
Leaving this as draft for now, as there may be more to add before the feature branch is ready, e.g., there may be some `kwarg` changes in `CoilsetOptimisationProblem`.
> Add deprecation warnings to old optimisation modules

- bluemira/balance_of_plant/plotting.py
- bluemira/builders/tools.py
- bluemira/codes/_freecadapi.py
- bluemira/codes/_polyscope.py
- bluemira/display/palettes.py
- bluemira/utilities/tools.py
- tests/display/test_displayer.py
- tests/display/test_palettes.py
It was annoying me that I couldnt see the colours in the terminal but I could in a jupyter notebook. Now it works in both places.
`pallette.as_hex()` to view hex representation or just `print(pallette)` to view the colours
> Allow viewing of palette colours in terminal

- bluemira/base/reactor.py
- bluemira/codes/_freecadapi.py
- bluemira/geometry/tools.py
- eudemo/config/build_config.json
- tests/codes/test_freecadapi.py
A few bugs have been fixed/ improvements have been made here:
1) Enums with the same value are overridden (I've now prefixed the file extension)
2) shape_name is always a tuple of two lists (It seems)
3) some filetypes need to be meshed before saving
4) getting a cad format from the name of the filetype is now possible
`cad_format="FREECAD"` `cad_format=CADFileType.FREECAD` and `cad_format="FCStd"` are all now possible as an addition to the latter 2
> 🎨 Improvements for freecad saving

- .github/workflows/comments.yml
PR comments CI fails if there is more than 1 artifact to download, the newest artifact is the first in the list so select that one.
> 💚 Fix PR comments when there are >1 artifacts returned

- bluemira/optimisation/_nlopt/optimiser.py
Part of  #2189 
ISRES usually hits its max eval limit so changed the message to a debug as recommended in the above epic
a debug message instead of a warning
> 🔊 Change max eval for ISRES to debug message

- bluemira/codes/interface.py
- bluemira/codes/plasmod/api/_solver.py
- bluemira/codes/plasmod/equilibrium_2d_coupling.py
- bluemira/codes/process/_solver.py
- eudemo/eudemo/power_cycle.py
- examples/codes/external_code.ex.py
- tests/codes/test_interface.py
RunMode is always imported and renamed, this just renames it to BaseRunMode anyway
Nothing major, although RunMode no longer exists.
> 🎨 Change base RunMode name

- bluemira/display/plotter.py
- tests/display/test_plotter.py
- tests/geometry/test_inscribed_rect.py
Closes #{ID}
This removes the defualt dictionaries from the PlotOptions dataclass it will enforce defaults unless explicitly removed or overridden.
It probably requires some thought about whether this is the direction we want to go
wire_options etc now are not cleared by default but use our defaults unless explicitly overridden.
> 🎨 Improve dictionary options for PlotOptions

- eudemo/README.md
Was just running the reactor example for some CAD pictures and noticed this path was wrong.
> Fix path to reactor script in eudemo README

- bluemira/utilities/opt_variables.py
Plotting an `OptVariableFrame` seems a bit unnecessary and doesn't add much over the tabulated version.
It also adds a dependency to display which breaks the dependency flow structure we're aiming for
> 🔥 Plotting an opt variable seems overkill

- bluemira/base/parameter_frame/_frame.py
- bluemira/base/parameter_frame/_parameter.py
- bluemira/utilities/opt_variables.py
- tests/base/parameterframe/test_parameterframe.py
Runtime error thrown if a subclass of a Parameterframe isn't annotated with @dataclass.
Supports empty pframe and optvarsframe.
> Added check for dataclass anontation for ParamFrame & OptVarFrame

- bluemira/codes/plasmod/equilibrium_2d_coupling.py
- bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
- bluemira/equilibria/fem_fixed_boundary/utilities.py
While checking on the fem rework with the new optimiser I ran into the 'Jackpot' message. This is an attempt to avoid that as dividing by 0 and sqrt -ves gives Nans which will always hit the end of the loop.
Secondly there was a weird array masking deletion thing that I dont think worked as it was intended
> Improve robustness of FEM solver

- bluemira/codes/_freecadapi.py
- tests/codes/test_freecadapi.py
- tests/geometry/test_data/test_circ.stp
Part::Feature does not link shapes properly in a freecad file so use Part::FeaturePython
see: https://wiki.freecad.org/Scripted_objects#Available_object_types
None
> 🐛 Fix freecad shape linking for saving

- bluemira/magnetostatics/circular_arc.py
- documentation/source/magnetostatics/doc_circular.py
- examples/magnetostatics/helmholtz_example.ex.py
- tests/magnetostatics/test_circuits.py
- tests/magnetostatics/test_circular_arc.py
> `CircularArcCurrentSource` API fixed to degrees, not radians

- bluemira/magnetostatics/circuits.py
- bluemira/magnetostatics/trapezoidal_prism.py
- documentation/source/magnetostatics/doc_trapezoidal.py
- tests/magnetostatics/test_circuits.py
- tests/magnetostatics/test_trapezoidal_prism.py
Closes #2592 
Fixes the issues in the aforementioned issue, but also:
* Moves the API of `TrapezoidalPrismCurrentSource` to use degrees and not radians
* Caps the inputs of valid angles to the necessary [0, 180)
* Deals with negative angles (allowed) and protects against mixed angles (not allowed)
> `TrapezoidalPrismCurrentSource` bugfixes and API changed to degrees, not radians

- bluemira/magnetostatics/biot_savart.py
- tests/magnetostatics/test_biot_savart.py
Closes #2593 
At present all I have done is fix the plotting, which was not showing the last point of a single filament. 
This sounds quite innocuous, but to avoid a whole bunch of length checking and closed/open checking for each individual array, I've simplified things down, at potentially some non-negligible additional computational cost. If Biot-Savart ever shows up in profiling, I can take another look at this.
> `BiotSavartFilament` plotting fixed

- bluemira/geometry/wire.py
- tests/geometry/test_wire.py
Closes #2598 
Fixes above bug. Preserves the convention of discretised geometry as being [[x], [y], [z]] rather than [[p1], [p2], [p3], [p4], ...]
> Fix `BluemiraWire.vertexes` for 3-vertex wire.

- bluemira/codes/_freecadapi.py
- bluemira/geometry/tools.py
- bluemira/geometry/wire.py
None, the issues are described here.
Some issues pointed out by a user James Roff can fixed with the changes in this PR.
Below are slight adaptions to the minimal reproductions supplied by him.
**A. Vertex returned from value_at throws when used with parameter_at and split_wire**:
```python
p = PictureFrame()
p.adjust_variable("x1", 2, lower_bound=0, upper_bound=5)
p.adjust_variable("x2", 13, lower_bound=10, upper_bound=20)
p.adjust_variable("z1", 13, lower_bound=8, upper_bound=15)
p.adjust_variable("z2", -11, lower_bound=-15, upper_bound=-8)
p.adjust_variable("ri", 2)
p.adjust_variable("ro", 5)
wire = p.create_shape()
dist = (13 + 11 - 2 * 2) + 0.25 * np.pi * 2
vertex = wire.value_at(distance=dist)
wire.parameter_at(vertex) # throws
first_half, second_half = split_wire(wire, vertex) # …
```
> Changes to fix J. Roff issues

- bluemira/codes/plasmod/equilibrium_2d_coupling.py
- bluemira/equilibria/fem_fixed_boundary/utilities.py
- eudemo/config/build_config.json
Closes #2574 
The FEM fixed boundary equilibrium solver does not do a great job converging in many cases. Right now, since #2484, the example of PLASMOD <-> fixed boundary equilibrium no longer converges.
I recently discovered that this is partly due to poor quality flux surfaces near the axis being extracted from the mesh and used to calculate profile quantities. 
Very commonly, the first one or two flux surfaces as extracted from the mesh (even with refinement) can be diamond- or square-shaped (with the number of points on a flux surface ranging from ~13-50 or so). They can oscillate between the two from one iteration to another (modifying V, g2 and g3), causing poor convergence.
This PR puts a crude number of points cut-off below which the flux surfaces are not used.
Really, we need a …
> FEM fixed boundary equilibrium solver - flux surface cut-off

- bluemira/equilibria/equilibrium.py
- bluemira/equilibria/plotting.py
- bluemira/equilibria/profiles.py
- tests/equilibria/test_equilibrium.py
Closes #2639
Adds `FixedPlasmaEquilibrium` to handle loading EQDSKs that come from fixed boundary solvers. I'm not sure what the convention is regarding extrapolation of poloidal magnetic flux outside of the plasma boundary.
It appears JETTO does not do this for you, so the resulting `FixedPlasmaEquilibrium` looks like this:
It would be easy enough to include extrapolation, but a little fiddly if other solvers actually do provide non-0 poloidal magnetic flux outside the plasma.
There is the outstanding issue of #318, which is not addressed here.
> Add `FixedPlasmaEquilibrium` for loading fixed boundary EQDSKs.

- .readthedocs.yaml
- conda/environment.yml
- documentation/source/conf.py
Our develop docs has been failing for the last week or so because to versioning changes. This hacks the versinoing about so it works again.
Because of how `importlib.metadata` works and because readthedocs only clones the last 50 commits, the version string in the header will break if the last tag >50 commits ago. In that instance we now just call the version `develop`
> 🐛Fix docs build

- bluemira/base/parameter_frame/_frame.py
- bluemira/codes/plasmod/params.py
- bluemira/codes/process/params.py
- tests/codes/test_interface.py
- tests/codes/test_param.py
Our examples CI broke because it is now included in `__dataclass_fields__` there may be a better fix than this.
https://github.com/Fusion-Power-Plant-Framework/bluemira/actions/runs/6294962951
This will have broken any external code runs I think...
> 🐛 Fix use of ClassVar in MappedParameterFrames

- bluemira/equilibria/coils/_coil.py
- bluemira/equilibria/coils/_grouping.py
- bluemira/equilibria/equilibrium.py
- bluemira/equilibria/optimisation/problem/base.py
- tests/equilibria/test_coils.py
- tests/equilibria/test_equilibrium.py
#2239
Closes #{ID}
If you try to initiailse an Equilibrium object with an eqdsk that doesnt have a coilset it fails with the new Coilset.
Added a user input option for a coilset when initiailse an Equilibrium and a dummy coilset that is created if no coilset is present.  Dummy coils are placed at the corners of the grid, and have current, dx, dz, j_max and b_max set to zero. A warning is printed if the dummy coilset is used. This should allow us to initiailse an eqdsk with no coilset until we have a permanent solution. 
> Temporary for Issue #2239 -  eqdsk without a coilset

- bluemira/equilibria/coils/_grouping.py
Closes #{ID}
:/ removing the control flag from Coil internals means that now when loading an EQDSK with passive coils, one has to manually assign those coils as non-controlled coils after initialisation.
> `Coil` remove control=False call

- bluemira/magnetostatics/polyhedral_prism.py
- tests/magnetostatics/test_polyhedral_prism.py
Closes #{ID}
So, I wrote another one just to check if there was something wrong with the first one I wrote (either in terms of implementation or theory). The results are identical to the first one (aside from some singularity I have yet to fully resolve). The geometry they use is the same though, so there's still potential for both to be wrong. I do cross-check with the TrapezoidalPrism geometry (in terms of points), but that isn't really directly used in the trapezoidal prism.
I think it is useful to have two kernels for this, because it means we can cross-benchmark some edge cases and singularities etc. I don't think it should be user-facing, and we should pick whichever one is more robust and faster (in that order). Still need a benchmark with a FE code to proceed.
I confirm that I …
> Add an alternative polyhedral VIM formulation

- documentation/source/conf.py
- requirements-develop.txt
Allows for sphinx upgrades, bumping to rc0 because python3.8 support dropped on the full release. 
> ⬆️ Update Myst-nb

- bluemira/builders/tf_coils.py
Fixed RippleConstrainedLengthGOP init signature: Closes #2719
Changed the parameters, so that:
|                         |     'ripple_wire' provided     |  'ripple_wire' not provided   |
|-------------------------|--------------------------------|-------------------------------|
|'separatrix' provided    | self.ripple_wire = ripple_wire<br />throw DeprecationWarning | self.ripple_wire = separatrix<br />throw DeprecationWarning |
|'separatrix' not provided| self.ripple_wire = ripple_wire | throw ValueError              |
No API breaking change, but the keyword argument 'separatrix' is tagged onto the end of of the init method of builder.tf_coils.RippleConstrainedLengthGOP.
> Papercut: Deprecating separatrix into ripple_wire

- bluemira/codes/plasmod/equilibrium_2d_coupling.py
- conftest.py
- tests/codes/plasmod/test_equilibrium.py
- tests/equilibria/fem_fixed_boundary/test_Solovev.py
- tests/equilibria/fem_fixed_boundary/test_fem_magnetostatic_2D.py
- tests/equilibria/fem_fixed_boundary/test_generated_data/.gitignore
- tests/geometry/test_tools.py
- tests/magnetostatics/test_finite_element_2d.py
- tests/magnetostatics/test_generated_data/.gitignore
- tests/mesh/test_generated_data/.gitignore
- tests/mesh/test_meshing.py
- tests/utilities/test_tools.py
Changes the default pytest temp directory to `generated_data/test_data` in the repo root unless overridden.
Removes all `test_generated_data` folders in tests
> 🧐 Setup default pytest temp dir for data

- bluemira/equilibria/plotting.py
Closes #{ID}
Sets the coilset's label z ordering to 100 to above all other plots in a figure.
> Coilset label z ordering

- bluemira/equilibria/optimisation/problem/_minimal_current.py
- bluemira/equilibria/optimisation/problem/_nested_position.py
- bluemira/equilibria/optimisation/problem/_position.py
None.
Use the same interface as TikhonovCOP.
Minor change to the init for the `MinimalCurrentCOP`.
> Standardise COP classes interfaces

- tests/base/parameterframe/test_parameterframe.py
This is one of the starts for python3.10 support.
`Parameter[str|list]` now implicitly works.
This is being merged into the python3.10 branch 
> ✅ Python310 accepts Union in parameterframes

- bluemira/fuel_cycle/tools.py
- bluemira/plasma_physics/reactions.py
Closes #2855 
Broke .. math:: or :math: lines that are too long. 
Some of the equations written with `quantity[unit]` inside the expression are simplified by removing the `[unit]`. This removes visual clutter while keeping the equation comprehensible. See the comments on #2855 for more details.
None
> Fixed docstring by breaking the too-long :math: lines.

- bluemira/base/constants.py
- bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
- bluemira/fuel_cycle/timeline.py
- bluemira/fuel_cycle/timeline_tools.py
Closes #2960
Collate random seed setting: sets the random number seed so our results in some cases are reproduceable.
Added the class `RNGSeeds `in `bluemira/base/constants.py`.
It sets random seeds to be used in functions that depend on random number generations:
- `collocation_points()` in `bluemira.equilibria.harmonics`,
- `generate_lognorm_distribution()`, `generate_truncnorm_distribution()`, and `generate_exponential_distribution()` in `bluemira.fuel_cycle.timeline_tools`,
and 
- `calculate_outages()` in `bluemira.fuel_cycle.timeline`
In case you add new functionalities in Bluemira in future that would depend on random number generations, it will be suggested to put a corresponding random seed in the `RNGSeeds` class too.
> Collate random seed setting

- bluemira/codes/interface.py
- bluemira/codes/process/_setup.py
- bluemira/codes/process/_teardown.py
Closes #2012
Adds a fix to the output params mapping (from process outputs to Bluemira params), when an output parameter name becomes obsolete.
None
> PROCESS - BM obsolete parameter names

- bluemira/display/plotter.py
- examples/geometry/plotting_tutorial.ex.py
- tests/display/test_plotter.py
Closes #2293 
Before the conditional statements relied on plotting options being None, however since default options exist this could never be true. This meant that when providing custom plotting options to a component post creation it was ignored and the default was used instead.
Wanted to change this so the following priority ordering existed:
1. component with non-default plotting options at creation
2. custom plotting options post-creation
3. default component plotting option
This was done by checking the various plotting options against their default values. Was not possible to check entire options dictionary against default but could however check the face colour, which is what was done until the full dictionary can be compared in a concise manner.
I confirm that I have completed …
> Fixed broken conditional statements in ComponentPlotter so now chooses correct plotting option

- bluemira/utilities/opt_variables.py
- eudemo/eudemo/maintenance/lower_port/duct_designer.py
- eudemo/eudemo_tests/maintenance/test_eq_port.py
- eudemo/eudemo_tests/maintenance/test_lower_port.py
- eudemo/eudemo_tests/maintenance/test_upper_port.py
Closes #2253 
Adds some lower port tests and does some small rearrangement.
There is a choice here which limit should be imposed on the straight section size.
1) scale to the maximum size but the minimum size is the user input (alternative 1)
2) limit to the user input (alternative 2)  **taken forward**
I've currently got 2) set up but up to the reviewer. I can't decide which is best.
The approximation of the TF coil being semi circular also leads to some failures in y point selection. For now I have just added a TODO (and will open an issue if agreed). This only affects extremes of input.
> Add lower port tests

- .pre-commit-config.yaml
- CITATION.cff
Zenodo at some point in the last 3.5 months decided that our CITATION.cff was no longer valid. This 'fixes' that and adds a pre-commit validation to hopefully catch this in future.
Once cff v1.3.0 comes out we should be able to add back multiple affiliations so the milestone says:
https://github.com/citation-file-format/citation-file-format/milestone/8
> 🐛 Fix Zenodo submission

- bluemira/base/reactor.py
Reactor will fail on some operations if where the reactor is defined imports annotations because they could be strings.
This gets the types based on those string or the class directly.
> 🐛 Fix getting component manager type if annotations imported

- bluemira/base/reactor_config.py
- eudemo/config/build_config.json
- tests/base/reactor_config/data/reactor_config.test.json
- tests/base/reactor_config/test_reactor_config.py
… config directory and accompanying tests
Closes #2965 
Added new directive to handle path expansion from config files, so will now be absolute file paths.
Added tests to check functionality.
> Reactor config addition for handling path expansion

- bluemira/codes/process/model_mapping.py
Adds ECRH O-mode cutoff with Zeff and Te (Physical review letters. 90. 075003) current drive efficiency model, iefrf = 13, as per PROCESS 
> ✅ Add iefrf = 13

- bluemira/base/designer.py
- eudemo/config/build_config.json
- eudemo/config/params.json
- eudemo/eudemo/ivc/__init__.py
- eudemo/eudemo/ivc/divertor_silhouette.py
- eudemo/eudemo/ivc/plasma_face.py
- eudemo/eudemo/params.py
Fixes angled targets
Closes #{ID}
> angled targets

- bluemira/geometry/parameterisations.py
Closes #1747 (well as many as is reasonable)
Add some of the missing labels to our geometry parameterisations
> ✨ Add more labels for Geometry Parameterisations

- bluemira/equilibria/find.py
- bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
- examples/equilibria/Spherical_Approximation_how_it_works.ex.py
- tests/equilibria/test_harmonics.py
Add option to create a uniform grid of sampled points for use in spherical harmonic approximation. 
> Add gridded collocation option

- bluemira/builders/coil_supports.py
- bluemira/codes/_freecadapi.py
- bluemira/equilibria/coils/_coil.py
- bluemira/equilibria/find.py
- bluemira/equilibria/flux_surfaces.py
- bluemira/gen_params.py
- bluemira/utilities/opt_tools.py
- bluemira/utilities/tools.py
- tests/equilibria/test_file.py
- tests/utilities/test_optimiser.py
numpy 1.25 deprecated float conversion for rank >0 scalars 
```python
float(np.array([5]))  # warning
float(np.array(5)) # ok
```
> Reduce warning count on python310

- bluemira/codes/_freecadapi.py
- bluemira/geometry/tools.py
Adds an optional transition type to the sweep shape API
stacked on top of a few PRs that need to go in first:
- #2887 
- #2320 
> Sweep shape API additions

- conda/environment.yml
Our CI was failing because c-blosc2 wasnt pinned in the conda env. The resultant environment crashes hard, it feels like a conda h5py interplay problem.
Until this is merged the CI will fail
We should possibly consider uv or similar for transient dependency management as it might help prevent situations like this
> 🧱 Missed pinning of c-blosc2

- bluemira/codes/process/api.py
- tests/codes/process/test_api.py
Sets are explicitly not ordered 🙄 so sometimes in the radiation work the data would be given to the wrong variables
> 🐛 Fix ordering of PROCESS impurity data outputs

- bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
- bluemira/equilibria/optimisation/harmonics/harmonics_constraint_functions.py
- bluemira/equilibria/optimisation/harmonics/harmonics_constraints.py
Closes #{ID}
Small changes to the SH constraint.
It adds the abiliaty to create an inverse version of the constraint, useful for turning it into two inequality constraints (instead of 1 equality).
Equality constraints are notriasly unstable/unusable in the NLOP optimisers.
They are also limited in number to the size of the state vector, which simpled that we were limited in the qaulity of our approximation.
> SH changes

- bluemira/equilibria/optimisation/constraints.py
> Papercut 3113 - use relative tolerances for constraints

- bluemira/magnetostatics/polyhedral_prism.py
- tests/magnetostatics/test_polyhedral_prism.py
Closes #3187 
When XS coords were given that were not local ie centered around (0, 0, 0) the _calculate_points function tried to transform it to global resulting in incorrect geometry.
Made a change to behaviour such that XS centroid is calculated and if it doesn't match up with origin the XS is translated so it is. This means that the length of the shape is now measured from centroid rather than the midpoint. Additionally means it isn't possible to create a prism or circuit that is displaced from the origin, so if that is desired the origin has to be displaced instead.
> Fix to incorrect PolyhedralPrismCurrentSource behaviour when inputted XS is in global not local coordinates

- bluemira/codes/_freecadapi.py
Closes #3192 
This is the easy fix for saving the CAD on the correct plane, should do some 
> 🐛 Hacky fix for CAD rotation saving bug

- bluemira/equilibria/run.py
Closes #{ID}
Creating this PR to highlight the fact that passing in max_currents has no effect as the `BreakdownCOP` ignores x0.
> `PulsedCoilsetDesign` Passing in max_currents has no effect

- .github/workflows/comments.yml
The number of artifacts we produce has increased therefore searching through a list of 30 (by default) often leads to not found pytest reports. I have increased this to the max for now.
It might be a good idea in future to go have a look at the graphql api instead 
> ⚡️ Increase number of artifacts requested for PR comments

- bluemira/magnetostatics/circuits.py
- bluemira/magnetostatics/polyhedral_prism.py
- tests/magnetostatics/test_circuits.py
- tests/magnetostatics/test_polyhedral_prism.py
Adding functionality to allow for ArbitraryPlanarPolyhedralXSCircuit to work when PolyhedralPrismCurrentSource has non equal end cap angles. Ideally a way to do it such that it is obvious when done and has to be intentional. Likely add a warning when used for this effect and to point out that there is reduction in accuracy of result when doing this. For use in STEP bluemira so can have TF coils with non-rectangular cross sections.
> Add functionality for uneven endcaps polyhedral current source

- bluemira/magnetostatics/circular_arc.py
- bluemira/magnetostatics/polyhedral_prism.py
- bluemira/magnetostatics/trapezoidal_prism.py
Helmholtz example failed with a numpy type casting problem. I've enforced float on the relevant arrays.
See https://github.com/Fusion-Power-Plant-Framework/bluemira/actions/runs/9153614018
> 🐛 Fix helmholz example

- tests/codes/process/utilities.py
Fixes a race condition in our tests that appears when running in parallel with xdist
> ✅ Fix process race condition in test

- bluemira/radiation_transport/flux_surfaces_maker.py
In #3265 I think this small change was missed. 
None
> 🐛 Fix radiation transport tests

- bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
- examples/equilibria/Spherical_Approximation_how_it_works.ex.py
- examples/equilibria/spherical_harmonic_approximation_basic_function_check.ex.py
- tests/equilibria/test_harmonics.py
Clip the equilibrium grid, so that the lower/upper-most coils are at the grid edges when inside the spherical harmonic approximation finding function. Prevents the use of an excessive number of required degrees in an approximation for cases where the LCFS appears to wrap around the divertor coils. 
> Clip the grid in the z-direction for SH LCFS fit metric

- bluemira/display/plotter.py
- bluemira/equilibria/optimisation/constraints.py
- bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
- bluemira/equilibria/plotting.py
- bluemira/radiation_transport/advective_transport.py
- bluemira/radiation_transport/radiation_profile.py
- examples/equilibria/Spherical_Approximation_how_it_works.ex.py
- examples/equilibria/spherical_harmonic_approximation_basic_function_check.ex.py
This PR changes some stylistic things about equilibria in an attempt to make them more professional looking.
|Before |After|
| ------------- | ------------- |
|<img src="https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/81617086/715e34a6-27cf-4dad-8c34-27689358ac0b" width="350"/> |<img src="https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/81617086/4f52fd58-4c8d-4a3e-89a1-0a86dc307143" width="370" height="90%"/>|
|Before |After|
| ------------- | ------------- |
|<img src="https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/81617086/441d5db1-0b31-4606-ba29-b97f94af08c4" width="350"/>|<img src="https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/81617086/2a09cfed-e05c-4736-8ed2-98177c0e40a3" width="370" height="90%"/>|
|Before |After|
| …
> 🎨 Improve plotting styles for equilibria

- bluemira/base/constants.py
- bluemira/fuel_cycle/cycle.py
- bluemira/fuel_cycle/lifecycle.py
- bluemira/fuel_cycle/timeline.py
- bluemira/fuel_cycle/tools.py
- bluemira/plasma_physics/collisions.py
- bluemira/plasma_physics/reactions.py
- bluemira/plasma_physics/rules_of_thumb.py
Closes #2853 with caveats: YR_TO_S and S_TO_YR cannot be removed completely as bluemira/plasma_physics/tools.py uses them, and cannot be converted to raw_uc there due to numba.jit.
Closes #2857 with caveats: get_species_data needs to be overhauled if this change were to be made, so it has been left unchanged, and may be ultimately solved in issue #2890.
Solves issue #2853 and #2857 simultaneously, so all temperature units are in keV or K (as opposed to a mix of eV/keV/K); and no more conversion multiplies (`*_TO_*`) are required.
bluemira.plasma_physics.rules_of_thumb.estimate_loop_voltage now takes in electron temperature in keV instead of eV.
bluemira.plasma_physics.collisions.spitzer_conductivity now takes in electron temperature in keV instead of eV.
I confirm that I have completed …
> Fix units and unit-conversion factors

- bluemira/codes/openmc/make_csg.py
- bluemira/radiation_transport/neutronics/make_pre_cell.py
- bluemira/radiation_transport/neutronics/neutronics_axisymmetric.py
- bluemira/radiation_transport/neutronics/slicing.py
Instead of cutting by bisecting tangents, we cut by ray-tracing from a common, central point above the divertor.
N/A
> Changed the cutting method of the divertor

- bluemira/equilibria/coils/_grouping.py
- bluemira/equilibria/equilibrium.py
- bluemira/equilibria/file.py
- bluemira/utilities/tools.py
- tests/equilibria/test_equilibrium.py
Closes #3294 Closes #645
#645 is probably an unfixable problem for raw eqdsk but this sidesteps that problem for json
Imports coil names into equilibrium objects
> Import coilset details from eqdsk if available

- .github/workflows/ci.yml
- bluemira/base/components.py
- bluemira/base/reactor.py
- bluemira/base/reactor_config.py
- conftest.py
- documentation/source/base/components.rst
- documentation/source/base/design_build.rst
- documentation/source/base/parameter.rst
- documentation/source/codes/codes.rst
- documentation/source/developer/logging.rst
- documentation/source/geometry/overview.rst
- documentation/source/materials/materials.rst
- documentation/source/mesh/mesh.rst
- documentation/source/optimisation/geometry.rst
- documentation/source/optimisation/optimisation_doc.rst
- pyproject.toml
- requirements-develop.txt
- tests/_helpers.py
- tests/geometry/test_coordinates.py
This is a possible addition to our CI suite that tests all code snippets in documentation and docstrings.
The documentation tests cant be run in parallel currently because each file shares a namespace.
The choice of using Sybil needs to be discussed but so far looks promising
> ✨ Test Documentation code snippets

- bluemira/radiation_transport/radiation_tools.py
- tests/radiation_transport/test_radiation_profile.py
- tests/radiation_transport/test_radiation_tools.py
> Add radiation tools tests

- bluemira/balance_of_plant/calculations.py
- bluemira/equilibria/coils/_coil.py
- bluemira/geometry/coordinates.py
- bluemira/magnetostatics/greens.py
- bluemira/magnetostatics/semianalytic_2d.py
- bluemira/plasma_physics/collisions.py
- bluemira/structural/element.py
…section_line
Addresses #1043
Added/amended docstrings for:
`bluemira.geometry.coordinates` :
`bluemira.plasma_physics.collisions`:
`bluemira.structural.element`:
`bluemira.balance_of_plant.calculations`:
`bluemira.magnetostatics.greens`:
`bluemira.magnetostatics.semianalytic_2d`:
`bluemira.equilibria.coils._coil`:
> (Few) Complete docstrings for physics/equation based functions

- bluemira/geometry/tools.py
- eudemo/eudemo/ivc/divertor_silhouette.py
- tests/geometry/test_tools.py
Improves some things around revolving open wires and smooths out demo divertor
> Minor improvements to revolving and bspline use 

- bluemira/codes/_freecadapi.py
- tests/codes/test_freecadapi.py
- tests/geometry/test_geometry.py
- tests/geometry/test_tools.py
- tests/geometry/test_wire.py
Closes #3037
The deserialiser is not necessarily stable but in 3037 there was a second bug because `Edges` over `OrderedEdges` was used.  
> 🐛 Enforce use of ordered edges

- examples/equilibria/Spherical_Approximation_how_it_works.ex.py
- examples/equilibria/spherical_harmonic_approximation_basic_function_check.ex.py
- examples/radiation_transport/heat_flux_calculation.ex.py
Somehow managed to missing adding COCOS into the examples
> 🐛 Fix missing cocos from examples

- bluemira/radiation_transport/radiation_profile.py
- examples/radiation_transport/radiation_calculation_solver_DEMO.py
- tests/radiation_transport/test_radiation_profile.py
Closes #3466 
Allowed for confinement time to vary from value of 0.1 ms in RadiationSource
> Added an option to configure the confinement time in RadiationSource

- .github/workflows/examples.yml
- bluemira/base/parameter_frame/_frame.py
- bluemira/radiation_transport/midplane_temperature_density.py
- bluemira/radiation_transport/radiation_tools.py
- examples/magnetostatics/finite_element_2D_single_coil.ex.py
- examples/radiation_transport/radiation_calculation_solver_DEMO.py
- tests/base/test_builder.py
Radiation max wall length was changed the wrong direction in magnitude in #3394 also the example was broken.
I've added the examples to the CI too since the process install action
> 🐛 Fix radiation_transport example and add examples to CI

- bluemira/utilities/tools.py
Closes #3533 
Removed extra indent and fixed typing in write_csv
> fix to write_csv typing and removed extra indent for adding col_names

- bluemira/magnetostatics/greens.py
Papercut #205 - three suggestions are made in this issue. The first addresses repetition and is covered by this pull request. The second is now a separate issue (#3273). The third was discussed by Bluemira developers but does not need to be implemented.  
Calculations that are repeated in multiple locations are now functions.
> Remove some repetition from Greens

- bluemira/equilibria/equilibrium.py
When an equilibrium was read in from eqdsk it would set the raw eqdsk as a varaible on the class instead of the instance of the class
> 🐛 Set _eqdsk on the instance not the class

- bluemira/codes/process/api.py
- bluemira/equilibria/coils/_coil.py
- bluemira/equilibria/coils/_field.py
- bluemira/equilibria/optimisation/constraint_funcs.py
- bluemira/equilibria/optimisation/constraints.py
- bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
- bluemira/equilibria/optimisation/problem/_breakdown.py
- bluemira/equilibria/run.py
- bluemira/utilities/tools.py
- eudemo/eudemo/blanket/__init__.py
- eudemo/eudemo/comp_managers.py
- eudemo/eudemo/ivc/wall_silhouette.py
- eudemo/eudemo/neutronics/run.py
- eudemo/eudemo/pf_coils/component_manager.py
- eudemo/eudemo/pf_coils/designer.py
- eudemo/eudemo/reactor.py
- eudemo/eudemo/tf_coils/tf_coils.py
- eudemo/eudemo/vacuum_vessel.py
- eudemo/eudemo_tests/blanket/test_blanket.py
- tests/equilibria/test_harmonics.py
- tests/equilibria/test_run.py
- Fixes some bugs where control coils were not explicitly selected in parts of the equilibria optimisation problems.
- Added rounding to field and force constraints (to 16 dp) which seems to stabilise them in local testing. I have it on good authority that the condition matrix of force constraint is infinite therefore very unstable. This seems to help a bit.
- Some general cleanup around properties on component managers
This was done while doing some work towards passive coils
> 🎨 Control coil enforcement, constraint stabilisation and general cleanup

- bluemira/base/logs.py
- bluemira/base/look_and_feel.py
- bluemira/codes/process/_run.py
- tests/base/test_logs.py
- tests/base/test_look_and_feel.py
Moves some logging mechanics to a lower level so it is collated, some work towards #3399 
> 🎨 Logging cleanup

- bluemira/display/plotter.py
Closes #3572
Papercut complete.
N/A
> Renamed the _data_to_plot attribute variable.

- bluemira/equilibria/find_legs.py
- bluemira/equilibria/flux_surfaces.py
- tests/equilibria/test_find.py
- tests/equilibria/test_flux_surfaces.py
find_legs.py 
- added function calculate_connection_length that takes target coordinate and can use either the flux surface geometry or field line tracer methods
- default rtol value changed in LegFlux
- converted get_legs_length to get_legs_length_and_angle
flux_surfaces.py 
- corrections (e.g. <0 set to <= 0) 
- fs input option for calculate_connection_length_fs
test_find.py 
- update for changed default tolerance. 
> Changes to get flux_surfaces and find_legs

- bluemira/equilibria/optimisation/harmonics/__init__.py
- bluemira/equilibria/optimisation/harmonics/harmonics_approx_functions.py
- documentation/source/examples.rst
- examples/equilibria/Spherical_Approximation_how_it_works.ex.py
- examples/equilibria/spherical_harmonic_approximation_basic_use.ex.py
- tests/equilibria/test_harmonics.py
Added an option to choose a flux surface with a given normalised flux, rather than the LCFS, for the spherical harmonic constraints. LCFS is still default. 
> Select fs for sh fit metric

- bluemira/equilibria/profiles.py
- documentation/source/equilibria/equilibria.rst
Closes #3625 
Fixed all issues related to Lao polynomials, including both Documentation and Implementation. Clarified the documentation as well.
N/A
----
📚 Documentation preview 📚: https://bluemira--3634.org.readthedocs.build/en/3634/
> Lao polynomial fixes

- CONTRIBUTING.md
- bluemira/equilibria/num_control.py
- bluemira/equilibria/physics.py
- bluemira/equilibria/profiles.py
- bluemira/equilibria/shapes.py
- bluemira/fuel_cycle/lifecycle.py
- bluemira/magnetostatics/circular_arc.py
- bluemira/magnetostatics/finite_element_2d.py
- bluemira/magnetostatics/polyhedral_prism.py
- bluemira/magnetostatics/semianalytic_2d.py
- bluemira/magnetostatics/trapezoidal_prism.py
- bluemira/materials/material.py
- bluemira/plasma_physics/reactions.py
- bluemira/plasma_physics/rules_of_thumb.py
- bluemira/plasma_physics/scaling_laws.py
- bluemira/radiation_transport/neutronics/constants.py
- documentation/source/conf.py
- documentation/source/fuel_cycle/fuel_cycle.rst
- documentation/source/magnetostatics/magnetostatics.rst
- examples/equilibria/fem_fixed_boundary/fem_boundary_conditions_example.py
- tests/equilibria/fem_fixed_boundary/test_Solovev.py
- tests/magnetostatics/test_semianalytic_2d.py
- tests/magnetostatics/test_trapezoidal_prism.py
- tests/plasma_physics/test_rules_of_thumb.py
- tests/plasma_physics/test_scaling_laws.py
Adds automatic doi links to papers  using both sphinx roles eg `:doi:` and directives `.. doi::`
----
📚 Documentation preview 📚: https://bluemira--3644.org.readthedocs.build/en/3644/
> DOI autolinking

- bluemira/radiation_transport/radiation_profile.py
- bluemira/radiation_transport/radiation_tools.py
- examples/radiation_transport/radiation_calculation_solver_DEMO.py
- tests/radiation_transport/test_radiation_profile.py
- tests/radiation_transport/test_radiation_tools.py
The core radiation was not calculated correctly because when accessing the tables from ADAS stored in PROCESS, Lz and Zeff where accessed with a reference temperature in keV instead of eV.
Besides the radiation calculation fix, a few checks related to the effective charge profiles and the average Z_eff value across the plasma were added.
Also added a scaling factor to use non-uniform electron temperature and electron density along the closed flux lines in the plasma core.
> Core radiation fix

- bluemira/geometry/tools.py
- bluemira/utilities/tools.py
Addresses #1043
As of commit [8c004bd2cecd9226fd98067b49ad5d61550578fb]
Added/amended docstrings for:
`bluemira.geometry.tools` :
`bluemira.utilities.tools` :
> Papercut: Add docstrings for equations 

- bluemira/codes/_freecadapi.py
- tests/codes/test_freecadapi.py
Closes #3528 
Added tests that cover:
- arcs produced by make_circle (arc length, start point, end point)
- arcs produced by make_circle using start_angle > end_angle (points match equivalent arc for start<end)
- arcs produced by make_circle_arc_3P (points match previous arcs for equivalent shape, fails when 3 points in line)
- ellipse arcs produced by make_ellipse (length is correct to value calculated from complete elliptic integral)
> Added tests for freecadapi from TODO list on circle and ellipse arcs

- .github/workflows/check_release_due.yml
- bluemira/base/reactor.py
- bluemira/codes/interface.py
- bluemira/codes/process/_setup.py
- bluemira/equilibria/find_legs.py
- bluemira/geometry/placement.py
- bluemira/geometry/plane.py
- bluemira/geometry/tools.py
- bluemira/materials/tools.py
- documentation/developer/adr/0005-record-cache-vs-recreate.md
- documentation/source/base/parameter.rst
- documentation/source/developer/logging.rst
- documentation/source/developer/release_workflow.rst
- documentation/source/introduction.rst
- documentation/source/optimisation/optimisation_doc.rst
- documentation/source/radiation_transport/radiation.rst
- documentation/source/utilities/utilities.rst
- examples/equilibria/Spherical_Approximation_how_it_works.ex.py
- examples/equilibria/coilset_opt_problem_tutorial.ex.py
- examples/equilibria/spherical_harmonic_approximation_basic_use.ex.py
- scripts/run_examples.py
Closes #3694 
Went through the entire codebase and made sure bluemira was only capitalised at the start of sentences. This only applied to docs files, docstrings or comments. Exceptions to this are when it is a thing from the code ie BluemiraSolid in which case it was left as it was.
----
📚 Documentation preview 📚: https://bluemira--3714.org.readthedocs.build/en/3714/
> Checks for bluemira capitalisation only at start of sentences

- .github/workflows/comments.yml
- scripts/format_warning_report.py
Part of #3604 
This updates to the lastest version of the [potiuk/get-workflow-origin](https://github.com/potiuk/get-workflow-origin) action. We should probably work out what to do about the fact it has been archived (fork, find an alternative)
> 👷 Update action version

- bluemira/codes/_freecadapi.py
- bluemira/geometry/tools.py
- tests/codes/test_freecadapi.py
- tests/geometry/test_tools.py
Closes #3589
Answered to-do comment, deleted it.
Raised GeometryError when colinear, instead of passing Part.OCCError through to the user.
> Handled error when making arc from 3 colinear points.

- bluemira/base/builder.py
- bluemira/builders/coil_supports.py
- bluemira/builders/cryostat.py
- bluemira/builders/divertor.py
- bluemira/builders/pf_coil.py
- bluemira/builders/radiation_shield.py
- bluemira/builders/thermal_shield.py
- bluemira/builders/tools.py
- bluemira/materials/cache.py
- eudemo/config/build_config.json
- eudemo/eudemo/blanket/builder.py
- eudemo/eudemo/comp_managers.py
- eudemo/eudemo/maintenance/duct_connection.py
- eudemo/eudemo/maintenance/lower_port/builder.py
- eudemo/eudemo/maintenance/port_plug.py
- eudemo/eudemo/reactor.py
- eudemo/eudemo/tf_coils/tf_coils.py
- eudemo/eudemo/vacuum_vessel.py
- eudemo/eudemo_tests/maintenance/test_upper_port.py
This PR setups the config and mechanics for specifying materials for each DEMO PhysicalCompoents in XYZ.
Part of the challenge in doing this is:
- Getting the necessary and correct material definitions data (in `materials.json`, `mixtures.json`)
- Specifying which components get what material
For some components, the geometry may need to be altered to define different parts of the component.
The breeding blanket for example does not have regions defined for the breeding zone, manifold etc.
Closes #{ID}
> Adding materials to DEMO

- bluemira/equilibria/plotting.py
- tests/equilibria/test_equilibrium.py
Small update so that plasma =True option works (False is currently default). 
> Out of date plot option

- bluemira/geometry/parameterisations.py
- tests/geometry/test_offset.py
Closes #3671 
It seems like this problem is no longer a problem with the recent dependency upgrades. Removing the comment.
Also adds a x failing test for #3586 that should pass when it is fixed
> 🎨 Princeton D fix and xfailing test

- bluemira/mesh/meshing.py
The meshing check was malformed because the buffer was never returned if `ismeshed == True`. This seemed to be to avoid remeshing the same object although it would never have worked in the situation without some more code in the else statement.
For now removed but could be added back as part of #2999 
See https://github.com/Fusion-Power-Plant-Framework/bluemira/actions/runs/12989499919 for passing examples after fix
> 🐛 Remove ismeshed check

- bluemira/geometry/wire.py
- examples/geometry/geometry_tutorial.ex.py
Figured this was small enough not to warrant an issue. Let me know if you would like one to be raised.
In the process of doing some work on the STEP first wall, it came to my attention that `BluemiraWire` creation can fail if you do not pass the boundary wires in the correct "end-to-start" order. This was not documented anywhere in the Bluemira docs, so I have added a few sentences to the `BluemiraWire` class docstring and the geometry tutorial.
None.
> Update documentation about BluemiraWire construction

- bluemira/structural/transformation.py
Closed papercut #3666
"Why does the less intuitive, simpler algebra form work better??"
Not certain of the answer, but as we have the safe _direction_cosine_matrix_debugging version to compare to the speedier _direction_cosine_matrix, it seems ok to remove it from papercut TODO's.
Have left as a NOTE in comments.
> TODO to NOTE

- bluemira/base/constants.py
Pint was warning about redefinition of ppm. The unit set it is in is enabled on context activation.
I have moved the extra unit definitions to there so ppm is available to be aliased to
> 🐛 Fix pint warning

- conda/environment.yml
- pyproject.toml
- requirements/conda.txt
- requirements/uv/all.txt
- requirements/uv/base.txt
- requirements/uv/develop.txt
- requirements/uv/examples.txt
Numba-scipy is holding us back with some dependencies. This PR uses my commit from my fork where I have cleaned up the repo and removed the pin on scipy. 
It should be removed in future.
This will allow the upgrade of scipy and possibly numpy (unless process is required)
> Use numba-scipy hash

- bluemira/codes/plasmod/equilibrium_2d_coupling.py
- bluemira/display/plotter.py
- bluemira/equilibria/analysis.py
- bluemira/equilibria/coils/_field.py
- bluemira/equilibria/coils/_tools.py
- bluemira/equilibria/diagnostics.py
- bluemira/equilibria/equilibrium.py
- bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
- bluemira/equilibria/find_legs.py
- bluemira/equilibria/optimisation/problem/_minimal_current.py
- bluemira/equilibria/physics.py
- bluemira/equilibria/plotting.py
- bluemira/equilibria/run.py
- bluemira/equilibria/solve.py
- bluemira/utilities/plot_tools.py
- bluemira/utilities/tools.py
- documentation/source/examples.rst
- eudemo/eudemo/equilibria/_designer.py
- examples/equilibria/anaylsis_toolbox_examples.ex.py
- examples/equilibria/coilset_opt_problem_tutorial.ex.py
- examples/equilibria/eudemo_2017.ex.py
- examples/equilibria/single_null.ex.py
- examples/equilibria/spherical_harmonic_approximation_basic_use.ex.py
- tests/equilibria/test_analysis.py
- tests/equilibria/test_equilibrium.py
- tests/equilibria/test_force_field.py
- tests/equilibria/test_optimisation.py
- tests/equilibria/test_st_equilibrium.py
#3376
Further additions/updates for the eq analysis feature branch.
See examples/equilibria/anaylsis_toolbox_examples.ex.py for how to use.
> Eq analysis tools update

- bluemira/codes/_freecadapi.py
- bluemira/geometry/base.py
- tests/geometry/test_bound_box.py
Closes #3818 
Updated the "optimal_bounding_box" attribute to one that uses FreeCAD's built-in "optimalBoundingBox" (added in the updated version of freecad.), as a property of BluemiraGeo, rather than a method.
`get_optimal_bounding_box()` (a method) -> `optimal_bounding_box` (a property)
Removed the need for the tolerance parameter as well.
> Used better optimal bounding box

- bluemira/geometry/parameterisations.py
Closes #3587 
Adds labels for height, top, upper, dz, flat, bottom, lower for PolySpline.
Since flat, upper, lower, top, bottom are fractions, labels for the lengths are used where these fractions are multiplied with the height.
Example labels after plotting
To reproduce the above plot:
```
from bluemira.geometry.parameterisations import PolySpline
test_spline = PolySpline(
{
"flat": {
"value": 0.3,
"lower_bound" : 0,
"upper_bound" : 1,
"description": "Fraction of straight outboard leg",
},
"z2": {
"value": 0.3,
"lower_bound" : -2,
"upper_bound" : 2,
"description": "Outer note vertical shift",
},
"tilt": {
"value": 25,
"lower_bound" : -45,
"upper_bound" : 45,
"description": "Outboard angle [degrees]",
}
}
)
import matplotlib.pyplot as plt
f, ax = plt.subplots()
test_spline.plot(ax=ax, …
```
> Add labels for height top upper dz flat bottom lower for PolySpline

- .github/workflows/actions/build/action.yml
- .github/workflows/examples.yml
- bluemira/codes/_freecadconfig.py
- conda/environment.yml
Avoids the need to do the steps described in #3734 and release [v2.5.0](https://github.com/Fusion-Power-Plant-Framework/bluemira/releases/tag/v2.5.0)
Upgrades pivy to the most recent version which includes the patch.
I have left the patch in the repo because it may take a while for people to update the env as said in the error message the patch will be removed by v2.8.0
None
> ⬆️ Upgrade pivy to v0.6.10

- bluemira/utilities/tools.py
- tests/utilities/test_tools.py
Loadspec used in get_module fialed with an index error if you passed in the string eg 'OCC'. It should have failed with a descriptive error.
> Fix loadspec index error

- bluemira/codes/_freecadapi.py
Quickly getting this in so no related issue.
The start and end point tangents for the FreeCAD API function `interpolate_bspline` were actually able to be set because of faulty logic. Fix of the logic has been made here.
N/A
> 🐛 Fix bug in interpolate_bspline related to tangents

- bluemira/equilibria/analysis.py
- bluemira/equilibria/plotting.py
- examples/equilibria/anaylsis_toolbox_examples.ex.py
The physics analysis plots where overpotting onto the previous plots when run as a python file rather than a notebook. This should remove this problem in the examples found in BM, BM training and STEP.
> Fix overplotting

- bluemira/codes/_freecadapi.py
- bluemira/display/auto_config.py
- bluemira/utilities/tools.py
There has been some reports of the qt cad viewer crashing with
```
QWidget: Must construct a QApplication before a QWidget
Aborted (core dumped)
```
this is not great and it is hard to see what we are doing wrong. So I've extracted all QApplication calls to one place and made it a try except instead.
Still needs a bit of checking
None
> 🏗️ Qtapp robustness improvement

- .github/workflows/examples.yml
Our examples were running on any push to any branch. It should only run on a PR merge so updating to only run on push to develop and main
> 👷 Run examples only on push to relevant branches

- .github/workflows/pin_dependencies.yml
uv 0.7.17 has a bug (14367) for finding links to dependencies. This avoids that version
> 🐛 Skip uv version for transient dependency pins

- .github/workflows/ci.yml
- .github/workflows/comments.yml
- scripts/install-conda.sh
This changes the default python version of bluemira to 3.11, 3.10 is still supported but now in a legacy mode.
We now also build the docs and lint with 3.12 (see #3857 for why)
Our new neutronics functionality around fast_ctd is not supported on python 3.10. All other functionality is currently still supported on 3.10 while our 3.10 support continues.
> 📌 Change default python version to 3.11
